### ISSUE TITLE
[Request] - GetAllData function

### ISSUE THREAD

**Issue by bombillazo** [mrousavy/react-native-mmkv#400] opened 2022-05-31 19:04 UTC
It would be great for debugging purposes to be able to print out the complete storage data with a single function call. I did not see such a feature in the docs or code.

**Comment by mrousavy** [comment] 2022-06-01 08:55
Hi, this is a duplicate of https://github.com/mrousavy/react-native-mmkv/issues/336

**Closed by mrousavy** 2022-06-01 08:55 UTC
