### ISSUE TITLE
3.0.1 iOS build issue with RN 0.75.2

### ISSUE THREAD

**Issue by divineniiquaye** [mrousavy/react-native-mmkv#726] opened 2024-08-28 13:16 UTC
I encountered this issue on my MacOS Sequoia 15.0 (Beta) with new architect enabled react native expo 51.0.31

```
Compiling react-native-mmkv Pods/react-native-mmkv » NativeMmkvModule.cpp

❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:24:83)

  22 | // The MMKVConfiguration type from JS
  23 | using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
> 24 |                                         std::optional<std::string>, std::optional<MmkvCxxMode>>;
     |                                                                                   ^ use of undeclared identifier 'MmkvCxxMode'
  25 | template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
  26 | 
  27 | // The TurboModule itself


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:25:29)

  23 | using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
  24 |                                         std::optional<std::string>, std::optional<MmkvCxxMode>>;
> 25 | template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
     |                             ^ use of undeclared identifier 'MMKVConfig'
  26 | 
  27 | // The TurboModule itself
  28 | class NativeMmkvModule : public NativeMmkvCxxSpec<NativeMmkvModule> {


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:25:72)

  23 | using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
  24 |                                         std::optional<std::string>, std::optional<MmkvCxxMode>>;
> 25 | template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
     |                                                                        ^ use of undeclared identifier 'MMKVConfig'
  26 | 
  27 | // The TurboModule itself
  28 | class NativeMmkvModule : public NativeMmkvCxxSpec<NativeMmkvModule> {


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:34:49)

  32 | 
  33 |   bool initialize(jsi::Runtime& runtime, std::string basePath);
> 34 |   jsi::Object createMMKV(jsi::Runtime& runtime, MMKVConfig config);
     |                                                 ^ unknown type name 'MMKVConfig'
  35 | };
  36 | 
  37 | } // namespace facebook::react


❌  (node_modules/react-native-mmkv/cpp/MmkvHostObject.h:20:41)

  18 | class MmkvHostObject : public jsi::HostObject {
  19 | public:
> 20 |   MmkvHostObject(const facebook::react::MMKVConfig& config);
     |                                         ^ no type named 'MMKVConfig' in namespace 'facebook::react'
  21 |   ~MmkvHostObject();
  22 | 
  23 | public:


❌  (node_modules/react-native-mmkv/cpp/MmkvHostObject.h:28:54)

  26 | 
  27 | private:
> 28 |   static MMKVMode getMMKVMode(const facebook::react::MMKVConfig& config);
     |                                                      ^ no type named 'MMKVConfig' in namespace 'facebook::react'
  29 | 
  30 | private:
  31 |   MMKV* instance;


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.cpp:38:65)

  36 | NativeMmkvModule::~NativeMmkvModule() {}
  37 | 
> 38 | jsi::Object NativeMmkvModule::createMMKV(jsi::Runtime& runtime, MMKVConfig config) {
     |                                                                 ^ unknown type name 'MMKVConfig'
  39 |   auto instance = std::make_shared<MmkvHostObject>(config);
  40 |   return jsi::Object::createFromHostObject(runtime, instance);
  41 | }

› Compiling react-native-mmkv Pods/react-native-mmkv » MmkvPlatformContextModule.mm
› Compiling react-native-mmkv Pods/react-native-mmkv » MmkvOnLoad.mm

❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:24:83)

  22 | // The MMKVConfiguration type from JS
  23 | using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
> 24 |                                         std::optional<std::string>, std::optional<MmkvCxxMode>>;
     |                                                                                   ^ use of undeclared identifier 'MmkvCxxMode'
  25 | template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
  26 | 
  27 | // The TurboModule itself


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:25:29)

  23 | using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
  24 |                                         std::optional<std::string>, std::optional<MmkvCxxMode>>;
> 25 | template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
     |                             ^ use of undeclared identifier 'MMKVConfig'
  26 | 
  27 | // The TurboModule itself
  28 | class NativeMmkvModule : public NativeMmkvCxxSpec<NativeMmkvModule> {


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:25:72)

  23 | using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
  24 |                                         std::optional<std::string>, std::optional<MmkvCxxMode>>;
> 25 | template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
     |                                                                        ^ use of undeclared identifier 'MMKVConfig'
  26 | 
  27 | // The TurboModule itself
  28 | class NativeMmkvModule : public NativeMmkvCxxSpec<NativeMmkvModule> {


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:34:49)

  32 | 
  33 |   bool initialize(jsi::Runtime& runtime, std::string basePath);
> 34 |   jsi::Object createMMKV(jsi::Runtime& runtime, MMKVConfig config);
     |                                                 ^ unknown type name 'MMKVConfig'
  35 | };
  36 | 
  37 | } // namespace facebook::react

› Compiling react-native-mmkv Pods/react-native-mmkv » MmkvHostObject.cpp

❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:24:83)

  22 | // The MMKVConfiguration type from JS
  23 | using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
> 24 |                                         std::optional<std::string>, std::optional<MmkvCxxMode>>;
     |                                                                                   ^ use of undeclared identifier 'MmkvCxxMode'
  25 | template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
  26 | 
  27 | // The TurboModule itself


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:25:29)

  23 | using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
  24 |                                         std::optional<std::string>, std::optional<MmkvCxxMode>>;
> 25 | template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
     |                             ^ use of undeclared identifier 'MMKVConfig'
  26 | 
  27 | // The TurboModule itself
  28 | class NativeMmkvModule : public NativeMmkvCxxSpec<NativeMmkvModule> {


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:25:72)

  23 | using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
  24 |                                         std::optional<std::string>, std::optional<MmkvCxxMode>>;
> 25 | template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
     |                                                                        ^ use of undeclared identifier 'MMKVConfig'
  26 | 
  27 | // The TurboModule itself
  28 | class NativeMmkvModule : public NativeMmkvCxxSpec<NativeMmkvModule> {


❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:34:49)

  32 | 
  33 |   bool initialize(jsi::Runtime& runtime, std::string basePath);
> 34 |   jsi::Object createMMKV(jsi::Runtime& runtime, MMKVConfig config);
     |                                                 ^ unknown type name 'MMKVConfig'
  35 | };
  36 | 
  37 | } // namespace facebook::react


❌  (node_modules/react-native-mmkv/cpp/MmkvHostObject.h:20:41)

  18 | class MmkvHostObject : public jsi::HostObject {
  19 | public:
> 20 |   MmkvHostObject(const facebook::react::MMKVConfig& config);
     |                                         ^ no type named 'MMKVConfig' in namespace 'facebook::react'
  21 |   ~MmkvHostObject();
  22 | 
  23 | public:


❌  (node_modules/react-native-mmkv/cpp/MmkvHostObject.h:28:54)

  26 | 
  27 | private:
> 28 |   static MMKVMode getMMKVMode(const facebook::react::MMKVConfig& config);
     |                                                      ^ no type named 'MMKVConfig' in namespace 'facebook::react'
  29 | 
  30 | private:
  31 |   MMKV* instance;

› Compiling react-native-mmkv Pods/react-native-mmkv » MiniPBCoder_OSX.cpp
› Compiling react-native-mmkv Pods/react-native-mmkv » MiniPBCoder.cpp
› Compiling react-native-mmkv Pods/react-native-mmkv » MemoryFile_Win32.cpp
› Compiling react-native-mmkv Pods/react-native-mmkv » MemoryFile_OSX.cpp
› Compiling react-native-mmkv Pods/react-native-mmkv » MemoryFile_Linux.cpp
› Compiling react-native-mmkv Pods/react-native-mmkv » MemoryFile_Android.cpp
› Compiling react-native-mmkv Pods/react-native-mmkv » MemoryFile.cpp
⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » MyApp/MyApp » Build Phases » 'Upload Debug Symbols to Sentry'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » MyApp/MyApp » Build Phases » '[CP-User] [RNFB] Core Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » MyApp/MyApp » Build Phases » '[CP-User] [RNFB] Crashlytics Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script


› 17 error(s), and 3 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by divineniiquaye** [comment] 2024-08-28 17:56
I've resolve the issue by using this patch:

```
diff --git a/node_modules/react-native-mmkv/cpp/MmkvHostObject.cpp b/node_modules/react-native-mmkv/cpp/MmkvHostObject.cpp
index 38ee310..2bd84ea 100644
--- a/node_modules/react-native-mmkv/cpp/MmkvHostObject.cpp
+++ b/node_modules/react-native-mmkv/cpp/MmkvHostObject.cpp
@@ -1,4 +1,4 @@
-//
+
 //  MmkvHostObject.cpp
 //  Mmkv
 //
@@ -69,11 +69,11 @@ MMKVMode MmkvHostObject::getMMKVMode(const facebook::react::MMKVConfig& config)
   if (!config.mode.has_value()) {
     return MMKVMode::MMKV_SINGLE_PROCESS;
   }
-  react::MmkvCxxMode mode = config.mode.value();
+  react::NativeMmkvMode mode = config.mode.value();
   switch (mode) {
-    case react::MmkvCxxMode::SINGLE_PROCESS:
+    case react::NativeMmkvMode::SINGLE_PROCESS:
       return MMKVMode::MMKV_SINGLE_PROCESS;
-    case react::MmkvCxxMode::MULTI_PROCESS:
+    case react::NativeMmkvMode::MULTI_PROCESS:
       return MMKVMode::MMKV_MULTI_PROCESS;
     default:
       [[unlikely]] throw std::runtime_error("Invalid MMKV Mode value!");
diff --git a/node_modules/react-native-mmkv/cpp/NativeMmkvModule.h b/node_modules/react-native-mmkv/cpp/NativeMmkvModule.h
index e0aaf82..b750555 100644
--- a/node_modules/react-native-mmkv/cpp/NativeMmkvModule.h
+++ b/node_modules/react-native-mmkv/cpp/NativeMmkvModule.h
@@ -20,9 +20,9 @@
 namespace facebook::react {
 
 // The MMKVConfiguration type from JS
-using MMKVConfig = MmkvCxxConfiguration<std::string, std::optional<std::string>,
-                                        std::optional<std::string>, std::optional<MmkvCxxMode>>;
-template <> struct Bridging<MMKVConfig> : MmkvCxxConfigurationBridging<MMKVConfig> {};
+using MMKVConfig = NativeMmkvConfiguration<std::string, std::optional<std::string>,
+                                        std::optional<std::string>, std::optional<NativeMmkvMode>>;
+template <> struct Bridging<MMKVConfig> : NativeMmkvConfigurationBridging<MMKVConfig> {};
 
 // The TurboModule itself
 class NativeMmkvModule : public NativeMmkvCxxSpec<NativeMmkvModule> {
```

**Comment by mrousavy** [comment] 2024-08-29 15:37
This is a duplicate of 
- https://github.com/mrousavy/react-native-mmkv/issues/725
- https://github.com/mrousavy/react-native-mmkv/issues/722
- and https://github.com/mrousavy/react-native-mmkv/issues/718

They were all visible in the issues page, please don't spam issues or create duplicates. We already have enough of them.

I am working on a fix and will release it soon - in the meantime you can [sponsor me on GitHub](https://github.com/sponsors/mrousavy) to buy me a coffee or say "thanks". 😃❤️

**Closed** 2024-08-29 15:48 UTC

**Comment by mrousavy** [comment] 2024-08-29 15:50
released in [react-native-mmkv 3.0.2](https://github.com/mrousavy/react-native-mmkv/releases/tag/v3.0.2) :rocket:

**Comment by RajeshPandey057** [comment] 2024-08-30 14:17
Still facing the same issue. With version 3.0.1 and 3.0.2 both

**Comment by amjadbouhouch** [comment] 2024-08-31 11:09
+1

**Comment by cookiedev23** [comment] 2024-08-31 15:58
+1

**Comment by dannyilyas** [comment] 2024-09-01 01:48
+ 1

**Comment by howljs** [comment] 2024-09-01 05:30
+1

**Comment by mrousavy** [comment] 2024-09-02 09:46
-1

**Comment by howljs** [comment] 2024-09-02 10:33
-1

> Everything is working fine. Just make sure that react-native is on version 0.75.x.

**Comment by maukoese** [comment] 2024-09-03 19:06
+1

**Comment by MikhailR1337** [comment] 2024-09-05 04:12
react-native: "0.75.2"
expo: "51.0.32"
mmkv: "3.0.2"

still the same issue during the building process on IOS

**Comment by baronha** [comment] 2024-09-10 14:48
+1

**Comment by batcodegen** [comment] 2024-09-15 11:27
for me updating my mac and xcode to latest update fixed the issue automatically

**Comment by adesugbaa** [comment] 2024-09-15 14:18
@batcodegen Both links do not show any information.

**Comment by eyupkoc29** [comment] 2024-09-22 12:37
❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:25:43)


   "expo": "~51.0.28",
 "react": "18.2.0",
    "react-dom": "18.2.0",
 "react-native-mmkv": "^3.0.2",

**Comment by dembeEdward** [comment] 2024-10-05 14:19
I was also facing the same issue with my iOS build and after having a look at `NativeMmkvModule.h` I noticed some definitions missing. I updated the file and the build worked fine. Here is the patch file 
[react-native-mmkv+3.0.2.patch](https://github.com/user-attachments/files/17266509/react-native-mmkv%2B3.0.2.patch)

**Comment by mrousavy** [comment] 2024-10-16 09:15
> "add new architecture" : nah "use this patch!": nah
> 
> Just use v2.12.2 and it works.

well yea thats what the README says at the top

![Screenshot 2024-10-16 at 11 14 46](https://github.com/user-attachments/assets/6bdfead3-83a6-4c39-b436-dd9b6d4a179e)

**Comment by n0xgg04** [comment] 2025-02-20 07:52
.
