### ISSUE TITLE
_reactNativeMmkv.getAllKeys() is not a function

### ISSUE THREAD

**Issue by gron01** [mrousavy/react-native-mmkv#47] opened 2021-04-08 14:16 UTC
Hello guys. I have 

![image](https://user-images.githubusercontent.com/46619747/114042167-dd90d800-988d-11eb-8103-83058bdf36d3.png)
this error.

My Code 
```
import { MMKV } from "react-native-mmkv";

const mmkvController = (key, defaultValue) => {
    const allKeys = MMKV.getAllKeys();
    const filtered = allKeys.filter((val) => val === key);
    if (filtered.length === 0) MMKV.set(key, defaultValue);
    return true
};

export default mmkvController
```

React Native Version: 0.63.3
React Native MMKV Version : 1.1.6 
React Version: 16.13.1

**Comment by mrousavy** [comment] 2021-04-08 14:25
1. Does it work on iOS?
2. Did you follow [the installation guide](https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md)?

**Comment by gron01** [comment] 2021-04-08 14:37
1 I don't know if it works on ios I don't have a mac computer
2 Yes i did it

**Comment by mrousavy** [comment] 2021-04-08 17:51
Could you test if it works without reanimated? Also, can you run the Example app?

**Comment by yuri-lomashko-itechart** [comment] 2021-04-15 15:45
Hello, I guess I receive the similar error on iOS when use `Fast Refresh` in app, while code writing. In `release` mode I don't receive it, but I'm not sure about the real world experience after shipping to store.

Do you have any ideas?

<details>
  <summary>ScreenShot</summary>
  
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-15 at 18 41 29](https://user-images.githubusercontent.com/54143988/114897797-40e4b200-9e1a-11eb-93af-355db39f15aa.png)
</details>

```
Error storing data [
TypeError: _$$_REQUIRE(_dependencyMap[3], "react-native-mmkv").MMKV.getBoolean is not a function.
(In '_$$_REQUIRE(_dependencyMap[3], "react-native-mmkv").MMKV.getBoolean(MIGRATED_KEY)', '_$$_REQUIRE(_dependencyMap[3], "react-native-mmkv").MMKV.getBoolean' is undefined)
]
```

React Native Version: 0.64.0
React Native MMKV Version : 1.1.6
React Version: 17.0.3

**Comment by mrousavy** [comment] 2021-04-15 17:34
@yuri-lomashko-itechart afaik this is a fast refresh issue. It's currently a bit difficult to correctly install JSI functions, so this will definitely be fixed with RN 0.65/0.66 (when TurboModules are actually usable). There should be no issues in the production/release app.

**Comment by somebody32** [comment] 2021-04-19 05:27
@mrousavy unfortunately, this is happening to me in production on ios and looks like a race condition affecting more often older phones: sometimes I receive a `u.MMKV.getBoolean is not a function` in Sentry.

is there any workaround for this? any way to retry?

**Comment by mrousavy** [comment] 2021-04-19 07:26
@somebody32 I'll investigate this.

**Comment by mrousavy** [comment] 2021-04-20 08:35
@somebody32 are you using Reanimated?

The problem here is that reanimated uses a way of initializing their JSI/Turbo- Module which I cannot use since it can only be used by one module. I'm limited by how ready TurboModules are in React Native, but I'm sure I'll come up with a temporary solution until it can get fully automatically initialized.

**Comment by somebody32** [comment] 2021-04-20 08:43
@mrousavy yes, but 1.x version (react-native-reanimated@1.13.3), as far as I know, it is not using turbo-modules yet?

**Comment by lfabl** [comment] 2021-04-23 22:51
For now, you can do your operations in a separate function. You can do a work like the visual in the function you just created. This problem will be fixed. Then you turn it back to its original state. I think the root of the problem is due to differences in the runtime of app.js and the runtime of MMKV.

![Ekran görüntüsü 2021-04-24 014731](https://user-images.githubusercontent.com/17149305/115937077-987cc080-a49f-11eb-90a6-5d89b6db2434.png)

**Comment by lfabl** [comment] 2021-04-23 22:52
Maybe running mmkv in index.js once will solve this situation. (to import.)

**Closed** 2021-06-04 09:47 UTC
