### ISSUE TITLE
Read main application's mmkv values from Notification Service (IOS)

### ISSUE THREAD

**Issue by pavelustenko** [mrousavy/react-native-mmkv#621] opened 2024-01-11 19:01 UTC
Hi!
I'm trying to read my app's mmkv storage from Notification Service extension in order to modify remote message with values which set in my main app, but I'm facing the problem that mmkv storage which opened in extension seem to be empty.
I'm using default mmkv configuration in both main app and Notification extension. 
Somewhere in app:
```
class Storage {
  mmkv = new MMKV();
  ...
 mmkv.set("string", "some string value");
}
```
My NotificationService.m is:
```
#import "NotificationService.h"
#import <MMKVAppExtension/MMKV.h>

@interface NotificationService ()

@property (nonatomic, strong) void (^contentHandler)(UNNotificationContent *contentToDeliver);
@property (nonatomic, strong) UNMutableNotificationContent *bestAttemptContent;

@end

@implementation NotificationService

- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {
  [MMKV initializeMMKV:nil];
  NSLog(@"didReceiveNotificationRequest");
  MMKV *mmkv=[MMKV defaultMMKV];
  [mmkv enumerateKeys:^(NSString *key, BOOL *stop) {
      if ([key isEqualToString:@"string"]) {
          NSString *value = [mmkv getStringForKey:key];
          NSLog(@"MMKV key: %@ = %@", key, value);
          *stop = YES;
      }
  }];
  
   self.contentHandler = contentHandler;
   self.bestAttemptContent = [request.content mutableCopy];
  self.bestAttemptContent.title = [NSString stringWithFormat:@"%@ [modified]", self.bestAttemptContent.title];
  self.bestAttemptContent.badge = [NSNumber numberWithInteger:-1];
  self.contentHandler(self.bestAttemptContent);
}

- (void)serviceExtensionTimeWillExpire {
    self.contentHandler(self.bestAttemptContent);
}

@end

```
But when I look into the console I don't see any MMKV key-value output.
What am I doing wrong?

**Comment by CodeByTarun** [comment] 2024-01-11 19:28
Hey, you need to use an app group in order to get it working, see the following:

https://github.com/mrousavy/react-native-mmkv#app-groups
https://github.com/Tencent/MMKV/wiki/iOS_tutorial#configuration (the multi-process accessing part)

**Comment by pavelustenko** [comment] 2024-01-12 14:58
@CodeByTarun 
Still no luck.
I created app group, changed both initialization calls in AppDelegate.m and NotificationService.m to
```
  NSString *myGroupID = @"group.com.ttyxx";
  // the group dir that can be accessed by App & extensions
  NSString *groupDir = [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:myGroupID].path;
  [MMKV initializeMMKV:nil groupDir:groupDir logLevel:MMKVLogInfo];
```
I also added following code to AppDelegate.m to be sure I could read this property from JS layer. 
```
  [mmkv setString:@"\"HELLO\"" forKey:@"string"];
```
It works.

But still no luck with Notification service
```
NSString *value = [mmkv getStringForKey:@"string"];
    NSLog(@"MMKV VALUE IS: %@", value);
```
value returns nil.

**Comment by pavelustenko** [comment] 2024-01-12 15:44
I changed Debug MMKV's log level to MMKVLogDebug
Both processes log the same folder
AppDelegate Log:

```
[I] <libMMKV.mm:132::+[MMKV initializeMMKV:groupDir:logLevel:]> groupDir: /private/var/mobile/Containers/Shared/AppGroup/9513AAB0-195C-4AF1-9C44-576A77E86427/mmkv
```
NotificationService Log:
```
[I] <libMMKV.mm:132::+[MMKV initializeMMKV:groupDir:logLevel:]> groupDir: /private/var/mobile/Containers/Shared/AppGroup/9513AAB0-195C-4AF1-9C44-576A77E86427/mmkv
```
Obviously the folder is the same. I have no clue what to do next.

**Comment by mrousavy** [comment] 2024-01-16 08:38
Did you add `AppGroup` to `Info.plist`? https://github.com/mrousavy/react-native-mmkv/blob/6fa83b5f30fdbf4f91f192d62d0cef6483106177/ios/MmkvModule.mm#L49-L57

**Comment by mrousavy** [comment] 2024-01-17 14:09
I think this is a duplicate of https://github.com/mrousavy/react-native-mmkv/issues/622

**Closed by mrousavy** 2024-01-17 14:09 UTC

**Comment by pavelustenko** [comment] 2024-01-24 17:00
@mrousavy 
>Did you add AppGroup to Info.plist?
Yes I did.
>I think this is a duplicate of https://github.com/mrousavy/react-native-mmkv/issues/622
Thank you for your tip, I'll check it.
