### ISSUE TITLE
Intermittent crashes on Android v8

### ISSUE THREAD

**Issue by waynezhang1995** [mrousavy/react-native-mmkv#431] opened 2022-07-19 20:48 UTC
Hi, we are seeing some crashes on Android with v8 engine when initializing MMKV
``` 
[5:24 PM] Fatal Exception: com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: method parameters should be array, js engine: v8, stack:
t.value@42.js:1:1567
Object.u [as install]@33.js:1:1580
e.createMMKV@938.js:1:1333
new c@937.js:1:1390
new t@935.js:1:2000
<unknown>@935.js:1:3289
h@2:1584
d@2:957
o@2:495
<unknown>@928.js:1:1829
```
We are on version `2.3.0` and the MMKV is instantiated like this:
```
class MMKVLocalStorage  {
  private readonly storage: MMKV;

  constructor() {
    this.storage = new MMKV({
      id: <some id>,
    });
  }
```
Any ideas?

**Comment by kylecesmat** [comment] 2022-07-20 19:35
Unable to create a minimal reproduction, and in fact unable to reproduce it ourselves. This error is only found in our crash reports.

We applied some symbolicating to get a better trace:

```
node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:186:callNativeSyncHook
Object.u [as node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:140:nonPromiseMethodWrapper
node_modules/react-native-mmkv/lib/module/createMMKV.js:43:createMMKV
new node_modules/react-native-mmkv/lib/module/MMKV.js:25:constructor
```

Only affecting Android users on V8. Current versions:
- "react-native": "0.67.3"
- "react-native-v8": "0.67.3-patch.0",
- `"v8-android-jit": "9.93.0"`

**Comment by mrousavy** [comment] 2022-07-21 11:26
I'm guessing that the error is here: https://github.com/mrousavy/react-native-mmkv/blob/f693645e610e267c8f46f6e28e196a7f7fc964c9/src/createMMKV.ts#L56 - but no idea why.

**Comment by mrousavy** [comment] 2022-07-21 11:28
Which line is line 43 in your `node_modules/react-native-mmkv/lib/module/createMMKV.js`?

**Comment by kylecesmat** [comment] 2022-07-21 14:52
> Which line is line 43 in your `node_modules/react-native-mmkv/lib/module/createMMKV.js`?

It maps to this line https://github.com/mrousavy/react-native-mmkv/blob/master/src/createMMKV.ts#L50

Possibly we could deploy a patch that splits apart these null checks and see which is failing? The thing we obviously don't understand is what is different between the runtimes of these failing devices and the other set of android users whose devices this is working on.

**Comment by kylecesmat** [comment] 2022-07-27 15:20
@mrousavy feel free to close this. We've drawn the conclusion that this is unrelated to mmkv and instead related to RAM bundling on Android which resulted in module resolution issues across a few different surfaces.

**Comment by mrousavy** [comment] 2022-07-28 11:10
Oh, I see - that's a weird issue!

**Closed by mrousavy** 2022-07-28 11:10 UTC
