### ISSUE TITLE
Android Failed Build

### ISSUE THREAD

**Issue by Hannes1** [mrousavy/react-native-mmkv#148] opened 2021-09-12 16:40 UTC
Hi, so I'm getting the following error when building:

```
[38/38] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libreactnativemmkv.so
FAILED: ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libreactnativemmkv.so
cmd.exe /C "cd . && C:\Users\customer\AppData\Local\Android\Sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi21 --gcc-toolchain=C:/Users/customer/AppData/Local/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/customer/AppData/Local/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -fexceptions -frtti -std=c++1y -DONANDROID -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libreactnativemmkv.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libreactnativemmkv.so CMakeFiles/reactnativemmkv.dir/src/main/cpp/cpp-adapter.cpp.o CMakeFiles/reactnativemmkv.dir/src/main/cpp/MmkvHostObject.cpp.o -LC:/Hannes/chatable-mobile-app/node_modules/react-native-mmkv/android/build/react-native-0.63.4.aar/jni/armeabi-v7a core/libcore.a -llog -lreactnativejni -landroid C:/Users/customer/AppData/Local/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/arm-linux-androideabi/libz.a -latomic -lm && cd ."
../../../../src/main/cpp/cpp-adapter.cpp:10: error: undefined reference to 'facebook::jsi::Value::asString(facebook::jsi::Runtime&) const &'
../../../../src/main/cpp/cpp-adapter.cpp:11: error: undefined reference to 'facebook::jsi::Value::~Value()'
../../../../src/main/cpp/cpp-adapter.cpp:11: error: undefined reference to 'facebook::jsi::Value::~Value()'
../../../../src/main/cpp/cpp-adapter.cpp:25: error: undefined reference to 'facebook::jsi::Value::asObject(facebook::jsi::Runtime&) const &'
C:/Hannes/chatable-mobile-app/android/../node_modules/react-native/ReactCommon/jsi\jsi/jsi.h:1241: error: undefined reference to 'facebook::jsi::JSError::JSError(facebook::jsi::Runtime&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >)'
C:/Hannes/chatable-mobile-app/android/../node_modules/react-native/ReactCommon/jsi\jsi/jsi.h:940: error: undefined reference to 'facebook::jsi::Value::~Value()'       
C:/Hannes/chatable-mobile-app/android/../node_modules/react-native/ReactCommon/jsi\jsi/jsi-inl.h:112: error: undefined reference to 'facebook::jsi::Value::~Value()'   
C:/Hannes/chatable-mobile-app/android/../node_modules/react-native/ReactCommon/jsi\jsi/jsi-inl.h:112: error: undefined reference to 'facebook::jsi::Value::~Value()'   
C:/Hannes/chatable-mobile-app/android/../node_modules/react-native/ReactCommon/jsi\jsi/jsi.h:966: error: undefined reference to 'facebook::jsi::Value::~Value()'       
../../../../src/main/cpp/MmkvHostObject.cpp:22: error: undefined reference to 'facebook::jsi::HostObject::~HostObject()'
C:/Hannes/chatable-mobile-app/android/../node_modules/react-native/ReactCommon/jsi\jsi/jsi.h:0: error: undefined reference to 'vtable for facebook::jsi::HostObject'   
C:/Users/customer/AppData/Local/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing its key function
../../../../src/main/cpp/MmkvHostObject.cpp:32: error: undefined reference to 'facebook::jsi::HostObject::~HostObject()'
../../../../src/main/cpp/MmkvHostObject.cpp:32: error: undefined reference to 'facebook::jsi::HostObject::~HostObject()'
C:/Hannes/chatable-mobile-app/android/../node_modules/react-native/ReactCommon/jsi\jsi/jsi.h:940: error: undefined reference to 'facebook::jsi::Value::~Value()'       
C:/Hannes/chatable-mobile-app/android/../node_modules/react-native/ReactCommon/jsi\jsi/jsi.h:961: error: undefined reference to 'facebook::jsi::Value::~Value()'       
CMakeFiles/reactnativemmkv.dir/src/main/cpp/MmkvHostObject.cpp.o:MmkvHostObject.cpp:vtable for MmkvHostObject: error: undefined reference to 'facebook::jsi::HostObject::set(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&)'
CMakeFiles/reactnativemmkv.dir/src/main/cpp/MmkvHostObject.cpp.o:MmkvHostObject.cpp:typeinfo for MmkvHostObject: error: undefined reference to 'typeinfo for facebook::jsi::HostObject'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

The problem is I'm using Reanimated 2 and WatermelonDB that uses jsi 
This is how I manually linked them before, will this not work with Mmkv?:
```
    @Override
    protected JSIModulePackage getJSIModulePackage() {
      return new JSIModulePackage() {
        @Override
        public List<JSIModuleSpec> getJSIModules(final ReactApplicationContext reactApplicationContext,
            final JavaScriptContextHolder jsContext) {
          List<JSIModuleSpec> modules = Arrays.asList();

          modules.addAll(new WatermelonDBJSIPackage().getJSIModules(reactApplicationContext, jsContext));
          modules.addAll(new MmkvModulePackage().getJSIModules(reactApplicationContext, jsContext)); //New
          modules.addAll(new ReanimatedJSIModulePackage().getJSIModules(reactApplicationContext, jsContext));
          return modules;
        }
      };
    }
```

**Comment by mrousavy** [comment] 2021-09-13 08:45
The way you manually link them should work fine, I wonder why JSI fails to link for you. What react-native version are you on?

**Comment by Hannes1** [comment] 2021-09-13 09:24
Using expo bare project so still on 63
```    
"react": "16.13.1",
"react-native": "0.63.4"
```

**Comment by kelvinpompey** [comment] 2021-09-14 13:25
@Hannes1 @mrousavy I've been having build issues with expo bare as well. I was able to get it to build with the following modification to CMakeLists.txt: 

add_library(reactnativemmkv  # <-- Library name
        SHARED
        "${NODE_MODULES_DIR}/react-native/ReactCommon/jsi/jsi/jsi.cpp"
        src/main/cpp/cpp-adapter.cpp
        src/main/cpp/MmkvHostObject.cpp
)

I also had to update the flipper version in my expo app to 0.105.0. 

This builds successfully but when I try to use MMKV I get the following error: 
[Tue Sep 14 2021 08:00:31.950]  ERROR    Error: Failed to create a new MMKV instance, the native initializer function does not exist. Is the native MMKV library correctly installed? Make sure to disable any remote debugger (e.g. Chrome) to use JSI!

**Comment by Duell10111** [comment] 2021-09-14 18:09
+1 Facing the same issue on v1.3.1 in a Expo SDK 42 bare project with Reanimated 2 as other JSI package.

**Comment by mrousavy** [comment] 2021-09-15 08:18
@kelvinpompey did you install the MMKV JSI package in your `MainApplication.java`? Would be great to have the adb logs when the app starts to find out if it correctly initializes.

**Comment by kelvinpompey** [comment] 2021-09-15 12:25
@mrousavy You were right. I can't believe I forgot that step having done it so many times. The app works now!  I created a PR with the fix. @Duell10111 @Hannes1

**Comment by renanmav** [comment] 2021-09-16 19:30
I also have an Expo bare app (SDK 42) and I'm trying to install `react-native-mmkv`

Not sure if is the same issue, but I'm having trouble when building for Android with gradle. I think the error message (shown below) says that I have multiple versions of JNI.

```
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'lib/x86_64/libreactnativejni.so' from inputs:
      - /home/renan/Z1/mobile/node_modules/react-native-mmkv/android/build/intermediates/library_jni/debug/jni
      - /home/renan/.gradle/caches/transforms-2/files-2.1/853500c88a1c7aa39cc2ed9d862c843a/jetified-react-native-0.64.2/jni
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```

I did the Android setup [mentioned here](https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md) (I have Reanimated2 installed)

#### Versions

```
expo@42.0.0
react@17.0.1
react-native@0.64.2
react-native-mmkv@1.3.1
react-native-reanimated@2.2.0
```

**Comment by mrousavy** [comment] 2021-09-17 10:35
@renanmav maybe [this SO post helps you](https://stackoverflow.com/questions/44954122/more-than-one-file-was-found-with-os-independent-path-lib-x86-libusb-so)

**Comment by Corliosity** [comment] 2021-09-20 08:11
Hello,

The Android Build is still failing in version 1.3.1.

The cause for the build is the cpp-adapter is failing during the android process.

Is there anything I am missing or why this is failing?

Thank you

**Comment by mrousavy** [comment] 2021-09-20 08:24
The logs you attached do not contain a build error.

**Comment by Corliosity** [comment] 2021-09-20 08:52
Sorry,

Here is one of the errors that is shown during the android build process
`
 1 error generated.
  [2/38] Building CXX object CMakeFiles/reactnativemmkv.dir/src/main/cpp/cpp-adapter.cpp.o
  FAILED: CMakeFiles/reactnativemmkv.dir/src/main/cpp/cpp-adapter.cpp.o
  /Users/andrew.corliss/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/andrew.corliss/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/andrew.corliss/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dreactnativemmkv_EXPORTS -I../../../../../MMKV/Core -I/Users/andrew.corliss/Documents/app/app/clients/apps/native/android/../node_modules/react-native/React -I/Users/andrew.corliss/Documents/app/app/clients/apps/native/android/../node_modules/react-native/React/Base -I/Users/andrew.corliss/Documents/app/app/clients/apps/native/android/../node_modules/react-native/ReactCommon/jsi -I/Users/andrew.corliss/Documents/app/app/clients/node_modules/react-native-mmkv/MMKV/Core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -fexceptions -frtti -std=c++1y -DONANDROID -Oz -DNDEBUG  -fPIC   -std=c++1z -MD -MT CMakeFiles/reactnativemmkv.dir/src/main/cpp/cpp-adapter.cpp.o -MF CMakeFiles/reactnativemmkv.dir/src/main/cpp/cpp-adapter.cpp.o.d -o CMakeFiles/reactnativemmkv.dir/src/main/cpp/cpp-adapter.cpp.o -c ../../../../src/main/cpp/cpp-adapter.cpp
  ../../../../src/main/cpp/cpp-adapter.cpp:2:10: fatal error: 'jsi/jsi.h' file not found
  #include <jsi/jsi.h>
`
Thank you for the quick response

**Comment by mrousavy** [comment] 2021-09-20 11:53
Is that a monorepo? I don't work with those, so I cannot test this - but if you find a way to fix this, shoot me a PR and I'd happily merge it! Similar issue: https://github.com/mrousavy/react-native-vision-camera/issues/340

**Comment by radko93** [comment] 2021-09-20 16:08
I integrated mmkv today and my build fails (this is not a monorepo). RN 0.65, with reanimated. In debug everything works. This is the CI stacktrace

```
> Task :app:mergeDevReleaseNativeLibs FAILED
5557
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
5558

5559
FAILURE: Build failed with an exception.
5560

5561
* What went wrong:
5562
Execution failed for task ':app:mergeDevReleaseNativeLibs'.
5563
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
5564
   > 2 files found with path 'lib/x86_64/libreactnativejni.so' from inputs:
5565
      - /home/runner/work/x/node_modules/react-native-mmkv/android/build/intermediates/library_jni/release/jni
5566
      - /home/runner/.gradle/caches/transforms-3/21e302c6531efb1b4963a78cc38fec93/transformed/jetified-react-native-0.65.1/jni
5567
     If you are using jniLibs and CMake IMPORTED targets, see
5568
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

**Comment by radko93** [comment] 2021-09-20 16:52
@renanmav adding:
```
packagingOptions {
        pickFirst 'lib/x86_64/libreactnativejni.so'
        pickFirst 'lib/armeabi-v7a/libreactnativejni.so'
        pickFirst 'lib/arm64-v8a/libreactnativejni.so'
        pickFirst 'lib/x86/libreactnativejni.so'
    }

to `android` in app/build.gradle fixes the issue for me.

**Comment by Corliosity** [comment] 2021-09-21 06:23
@mrousavy yes it is a monorepo.  I did manage to create a work around in the build.gradle.  I will see if i can have a look at how to make it adaptable.

**Comment by Corliosity** [comment] 2021-09-21 12:09
Hello a little update :  It seems that #151 should already solve the issue I see it was merged 6 days ago but it has not been released.

Is there any ETA on when this will happen?

Thanks

**Comment by mrousavy** [comment] 2021-09-21 12:13
Oh wow, I completely forgot about that. My bad, been really busy lately - will publish an update now hopefully everything goes smooth!

**Comment by mrousavy** [comment] 2021-09-21 12:17
1.3.2 published, let me know if it builds for you guys.

**Comment by smallzZz8** [comment] 2021-09-23 00:35
I am also getting this error. Is there a fix yet?

**Comment by mrousavy** [comment] 2022-01-19 10:45
Please check if v2.0.0 works for you guys, I think I fixed this error :)

**Closed** 2022-01-19 10:52 UTC

**Comment by Rc85** [comment] 2022-07-10 23:41
Added `react-native-code-push` and I started getting this error. I was using version 2.3.3 and build would fail with this error.
```
C/C++: ninja: error: '../../../../build/react-native-0.68.0.aar/jni/armeabi-v7a/libjsi.so', needed by '../../../../build/intermediates/cxx/RelWithDebInfo/395q2yc5/obj/armeabi-v7a/libreactnativemmkv.so', missing and no known rule to make it
```
Upgraded to version 2.4.3 and build succeeds, but opening my crashes immediately. This is on react-native 0.68.0. `adb logcat` shows.
```
07-10 16:36:14.361  9054  9090 I MMKV    : Loading C++ library...
07-10 16:36:14.365  9054  9090 E ReactNativeJS: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreactnativemmkv.so" not found, js engine: hermes
07-10 16:36:14.366  9054  9090 E ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
07-10 16:36:14.366  9054  9090 E ReactNativeJS:       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
07-10 16:36:14.371  9054  9091 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
07-10 16:36:14.371  9054  9091 E AndroidRuntime: Process: com.my_takeouts_delivered, PID: 9054
07-10 16:36:14.371  9054  9091 E AndroidRuntime: com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreactnativemmkv.so" not found, js engine: hermes, stack:
07-10 16:36:14.371  9054  9091 E AndroidRuntime: callNativeSyncHook@1:156619
07-10 16:36:14.371  9054  9091 E AndroidRuntime: nonPromiseMethodWrapper@1:153811
07-10 16:36:14.371  9054  9091 E AndroidRuntime: createMMKV@1:2133241
07-10 16:36:14.371  9054  9091 E AndroidRuntime: MMKV@1:2132253
07-10 16:36:14.371  9054  9091 E AndroidRuntime: anonymous@1:2130452
07-10 16:36:14.371  9054  9091 E AndroidRuntime: loadModuleImplementation@1:61272
07-10 16:36:14.371  9054  9091 E AndroidRuntime: guardedLoadModule@1:60821
07-10 16:36:14.371  9054  9091 E AndroidRuntime: metroRequire@1:60449
07-10 16:36:14.371  9054  9091 E AndroidRuntime: anonymous@1:2120893
07-10 16:36:14.371  9054  9091 E AndroidRuntime: loadModuleImplementation@1:61272
07-10 16:36:14.371  9054  9091 E AndroidRuntime: guardedLoadModule@1:60821
07-10 16:36:14.371  9054  9091 E AndroidRuntime: metroRequire@1:60449
07-10 16:36:14.371  9054  9091 E AndroidRuntime: anonymous@1:2117746
07-10 16:36:14.371  9054  9091 E AndroidRuntime: loadModuleImplementation@1:61272
07-10 16:36:14.371  9054  9091 E AndroidRuntime: guardedLoadModule@1:60821
07-10 16:36:14.371  9054  9091 E AndroidRuntime: metroRequire@1:60449
07-10 16:36:14.371  9054  9091 E AndroidRuntime: anonymous@1:1517019
07-10 16:36:14.371  9054  9091 E AndroidRuntime: loadModuleImplementation@1:61272
07-10 16:36:14.371  9054  9091 E AndroidRuntime: guardedLoadModule@1:60821
07-10 16:36:14.371  9054  9091 E AndroidRuntime: metroRequire@1:60449
07-10 16:36:14.371  9054  9091 E AndroidRuntime: anonymous@1:1078792
07-10 16:36:14.371  9054  9091 E AndroidRuntime: loadModuleImplementation@1:61272
07-10 16:36:14.371  9054  9091 E AndroidRuntime: guardedLoadModule@1:60821
07-10 16:36:14.371  9054  9091 E AndroidRuntime: metroRequire@1:60449
07-10 16:36:14.371  9054  9091 E AndroidRuntime: anonymous@1:1077899
07-10 16:36:14.371  9054  9091 E AndroidRuntime: loadModuleImplementation@1:61272
07-10 16:36:14.371  9054  9091 E AndroidRuntime: guardedLoadModule@1:60821
07-10 16:36:14.371  9054  9091 E AndroidRuntime: metroRequire@1:60449
07-10 16:36:14.371  9054  9091 E AndroidRuntime: anonymous@1:882902
07-10 16:36:14.371  9054  9091 E AndroidRuntime: loadModuleImplementation@1:61272
07-10 16:36:14.371  9054  9091 E AndroidRuntime: guardedLoadModule@1:60821
07-10 16:36:14.371  9054  9091 E AndroidRuntime: metroRequire@1:60449
07-10 16:36:14.371  9054  9091 E AndroidRuntime: anonymous@1:572367
07-10 16:36:14.371  9054  9091 E AndroidRuntime: loadModuleImplementation@1:61272
07-10 16:36:14.371  9054  9091 E AndroidRuntime: guardedLoadModule@1:60821
07-10 16:36:14.371  9054  9091 E AndroidRuntime: metroRequire@1:60449
07-10 16:36:14.371  9054  9091 E AndroidRuntime: anonymous@1:67655
07-10 16:36:14.371  9054  9091 E AndroidRuntime: loadModuleImplementation@1:61272
07-10 16:36:14.371  9054  9091 E AndroidRuntime: guardedLoadModule@1:60778
07-10 16:36:14.371  9054  9091 E AndroidRuntime: metroRequire@1:60449
07-10 16:36:14.371  9054  9091 E AndroidRuntime: global@1:60035
07-10 16:36:14.371  9054  9091 E AndroidRuntime:
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
07-10 16:36:14.371  9054  9091 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
```
