### ISSUE TITLE
MMKV storage file grows until app crash

### ISSUE THREAD

**Issue by ryskin** [mrousavy/react-native-mmkv#440] opened 2022-08-05 02:15 UTC
The library is great but one crucial issue doesn't give me chance to use it.

And it grows by stop 64Mb, 128Mb etc.
If I use slow FS storage, the file size never becomes more than 15Mb. I also used the console log to check the size of the string.

It's working really fast and I want to use that, but with every rewriting, it becomes more significant. I checked key is always stable.

<img width="176" alt="image" src="https://user-images.githubusercontent.com/3756722/182987087-8def5c84-0bd0-4caa-b3bd-acc054901b99.png">

"react-native-mmkv": "^2.4.3",
"react-native": "0.66.3",

**Comment by mrousavy** [comment] 2022-08-05 07:53
How often are you writing to MMKV? It's not a database, it's a memory map key value storage.

**Comment by ryskin** [comment] 2022-08-10 15:26
> How often are you writing to MMKV? It's not a database, it's a memory map key value storage.

I'm writing when my state change with a throttling. I use it with redux-persist.
But why does the size of the file grow? As I mention before now I use FS storage and it's significantly slower but file size grows to 15Mb.

**Comment by ramirobg94** [comment] 2022-09-09 11:09
Other with the same problem:

Check  the explanation here https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/286

Seems that the Key Value doesn't overwrite the value, just add a new row into the storage.

**Comment by mrousavy** [comment] 2022-10-07 18:14
Possibly related? https://github.com/mrousavy/react-native-mmkv/issues/397

**Comment by aLemonFox** [comment] 2022-10-07 19:54
@mrousavy to clear things up, does mmkv insert a new row for every setter, without overwriting the previous value? If so, how can we properly clear 'old' entries?

**Comment by shawarmaz** [comment] 2023-01-21 09:53
@aLemonFox have you tried removing the previous entry before setting the new one?

**Comment by JacobFJ** [comment] 2023-01-29 13:27
Confirming this contributes to my app crashes. The memory is hogging in Android 12 Go edition which typically 2GB or less ram.

**Comment by ramirobg94** [comment] 2023-02-01 09:50
@shawarmaz  this is dangerous because you can get into two cases:

1 -> async delete, then async write -> maybe write is too slow so there is no advantage to using mmkv
2 -> race condition can maybe the new data be deleted

I see the point on how this memory is designed but should have some cleaning method to reduce the memory consumption, there is no point in keeping dozens of versions (Is there any method to recover previous versions? I think that no, so it is pointless)

**Comment by shawarmaz** [comment] 2023-02-01 10:22
@ramirobg94 neither of those cases apply because the calls are _sync_. To be clear that means _not async_.

**Comment by mrousavy** [comment] 2023-02-01 11:21
This is apparently how Tencent/MMKV is designed.

**Comment by arthurgeron-work** [comment] 2023-02-07 16:23
Checking if it exists and deleting before set seems to have worked I've used patch-package, but I can open a pr with the fix:
```diff
diff --git a/node_modules/react-native-mmkv/lib/module/MMKV.js b/node_modules/react-native-mmkv/lib/module/MMKV.js
index 8856aea..9cbe764 100644
--- a/node_modules/react-native-mmkv/lib/module/MMKV.js
+++ b/node_modules/react-native-mmkv/lib/module/MMKV.js
@@ -45,6 +45,12 @@ export class MMKV {
   }
   set(key, value) {
     const func = this.getFunctionFromCache('set');
+    const contains = this.getFunctionFromCache('contains');
+    if (key && contains(key)) {
+      console.log('fsk key exists, deleting first!');
+      const _delete = this.getFunctionFromCache('delete');
+      _delete(key);
+    }
     func(key, value);
     this.onValuesChanged([key]);
   }
```

**Comment by shawarmaz** [comment] 2023-02-07 16:37
I don’t think this should be merged, maybe just a doc update. You can just wrap the method yourself.

**Comment by arthurgeron-work** [comment] 2023-02-07 20:48
I don't think this should be left as is, having it fill up memory is a serious issue, having it go a little slower is much better than having it crash your app.

**Comment by shawarmaz** [comment] 2023-02-08 10:34
Again, this is how mmkv is designed. You can wrap the method yourself. Wrapping it lib-level would give new non-mmkv semantics to the lib. To keep it 💯 mmkv, the actual solution to this issue is mmkv’s `trim` method.

@mrousavy , what was the issue with this PR?

https://github.com/mrousavy/react-native-mmkv/pull/461

**Comment by shawarmaz** [comment] 2023-02-08 19:11
Read this https://github.com/Tencent/MMKV/issues/610

**Comment by arthurgeron-work** [comment] 2023-02-09 00:11
So it's either delete and trim manually or move to another lib, gotcha.

**Comment by arthurgeron-work** [comment] 2023-02-09 00:15
Another thing is that it seems like trim isn't a exposed method

**Comment by ryskin** [comment] 2023-02-09 02:19
I don't know, I started to use other MMKV libraries and problem disappear, file is small and works like charm

**Comment by codering** [comment] 2023-02-09 03:52
> I don't know, I started to use other MMKV libraries and problem disappear, file is small and works like charm

which lib？

**Comment by ryskin** [comment] 2023-02-09 06:14
I'm thinking not good to post links to other libraries here, but you can google only 2 main libraries available for react-native

**Comment by arthurgeron** [comment] 2023-02-09 07:36
> > I don't know, I started to use other MMKV libraries and problem disappear, file is small and works like charm
> 
> which lib？
 react-native-mmkv-storage works just fine

**Comment by mrousavy** [comment] 2023-02-09 09:52
> @mrousavy , what was the issue with this PR? https://github.com/mrousavy/react-native-mmkv/pull/461

@shawarmaz I found out that printing the total size after doing a trim made no difference, so I wasn't able to reproduce your error. I could take another look, but we wanna find the right solution here without sacrificing speed :)

Can you guys create a reproduceable example? Is this on Android only, or iOS too?

**Comment by shawarmaz** [comment] 2023-02-09 15:49
Personally I just wrapped writes with preprended deletes and called it a day. No noticeable difference in write performance. 

If you're testing against high volume of writes or high write size, you're not using the right tool for the job. [The official Tencent/MMKV repo benchmarks it against `NSUserDefaults/SharedUserPreferences`](https://github.com/Tencent/MMKV#performance-1) which tells you all you need to know about its intended usage i.e. not as a local runtime database. 

> [If you have a relatively small collection of key-values that you'd like to save, you should use the SharedPreferences APIs.](https://developer.android.com/reference/android/content/SharedPreferences)

> [The NSUserDefaults class provides a programmatic interface for interacting with the defaults system. The defaults system allows an app to customize its behavior to match a user’s preferences.](https://developer.apple.com/documentation/foundation/nsuserdefaults)

IMO the main selling point of MMKV is not speed but having a unified API for use cases that would have otherwise required NSUserDefaults/SharedUserPreferences.  

If you want to store application _data_ like chat messages or POI geopoints etc, use the right tool for the job i.e. something else. Even if `trim` was available everybody would be like wtf why do I need to do this. It's counterintuitive because you think MMKV is something that it is not. 

This may be a case of false advertisement around MMKV at large. Thoughts welcome

**Comment by aLemonFox** [comment] 2023-02-09 16:03
@shawarmaz I think you're right. I'm struggling with this too. 
Are there any other good reactive key value store libraries available which are not based on this? I can't seem to find any. They are either like AsyncStorage (async, not reactive) or WatermelonDB (full db, want key value store like Redis).

**Comment by shawarmaz** [comment] 2023-02-09 16:23
@aLemonFox just use this lib and wrap writes with a preprended delete
```js
  setItem: (key, value) => {
    storage.delete(key)
    storage.set(key, value);
    return Promise.resolve(true);
  },
```
...or just unsexy `AsyncStorage` whose writes overwrite and also does not load entire data from cold storage in memory. 

Which in fact also illustrates that comparisons/benchmarks between `AsyncStorage` and MMKV are inherently false/misleading.

**Comment by shawarmaz** [comment] 2023-02-09 16:50
@aLemonFox Btw mmm MMKV is not reactive

**Comment by arthurgeron-work** [comment] 2023-02-09 21:32
> @aLemonFox Btw mmm MMKV is not reactive



> Personally I just wrapped writes with preprended deletes and called it a day. No noticeable difference in write performance.
> 
> If you're testing against high volume of writes or high write size, you're not using the right tool for the job. [The official Tencent/MMKV repo benchmarks it against `NSUserDefaults/SharedUserPreferences`](https://github.com/Tencent/MMKV#performance-1) which tells you all you need to know about its intended usage i.e. not as a local runtime database.
> 
> > [If you have a relatively small collection of key-values that you'd like to save, you should use the SharedPreferences APIs.](https://developer.android.com/reference/android/content/SharedPreferences)
> 
> > [The NSUserDefaults class provides a programmatic interface for interacting with the defaults system. The defaults system allows an app to customize its behavior to match a user’s preferences.](https://developer.apple.com/documentation/foundation/nsuserdefaults)
> 
> IMO the main selling point of MMKV is not speed but having a unified API for use cases that would have otherwise required NSUserDefaults/SharedUserPreferences.
> 
> If you want to store application _data_ like chat messages or POI geopoints etc, use the right tool for the job i.e. something else. Even if `trim` was available everybody would be like wtf why do I need to do this. It's counterintuitive because you think MMKV is something that it is not.
> 
> This may be a case of false advertisement around MMKV at large. Thoughts welcome

It's not only falsely advertised, it's broken by design. Moving from async to mmkv is like switching to a bmw but that suddenly crashes into a lamp post if you push it too hard. 

Anyway, we need to test to be sure that prepending delete to write calls does actually fix the leak.

**Comment by arthurgeron-work** [comment] 2023-02-09 21:42
> @aLemonFox Btw mmm MMKV is not reactive

I think local storage should not be reactive, for that it's better to actually use something like Zustand or Redux and persist that data on specific moments, either with a specific solution or something like mmkv

**Comment by shawarmaz** [comment] 2023-02-10 00:16
> It's not only falsely advertised, it's broken by design. Moving from async to mmkv is like switching to a bmw but that suddenly crashes into a lamp post if you push it too hard.
> 
> Anyway, we need to test to be sure that prepending delete to write calls does actually fix the leak.

@arthurgeron No it's not broken by design, it is your understanding of its design that is broken. It is extremely efficient at what it is designed for, surely everyone touting its benefits aren't idiots. Did you even read my reply you quoted? Going from AsyncStorage to MMKV when you have a lot of high-write data is like trying to park a schoolbus in your garage.

**Comment by arthurgeron-work** [comment] 2023-02-10 12:24
Regular use of a lib that does not describe itself as "not production ready" should never cause a crash regardless

**Comment by shawarmaz** [comment] 2023-02-10 12:44
It is definitely production ready. For some unknown reason, you just don’t want to understand what it’s for. 

Stop spreading such misinformation and communicate constructively instead of ranting and complaining @arthurgeron

**Comment by arthurgeron-work** [comment] 2023-02-10 13:40
Please explain how I am wrong, regular but intense use of this won't generate a crash? Writes don't create new allocations and leave old ones hanging?

**Comment by arthurgeron-work** [comment] 2023-02-10 14:25
Tencent MMKV used as a base for this lib works in a way that wasn't clearly advertised, sine clearly RN MMKV intended to be used to store info like it was done to Async Storage, which causes the crash, still, not safe to use in  production, even with workarounds, because it by default uses it as a "DB"of sorts which it isn't intended to do in the first place, but the rn lib is advertised for such use.

I'm not going to reply on that subject any longer, reasons for that should be beyond clear given your passive-agressive and vulgar vocabulary, which only gets in the way of a clear respectful discussion.

**Comment by shawarmaz** [comment] 2023-02-10 14:35
Glad things are finally clear.

This does require an update to the docs tho.

@mrousavy if you agree with that has been said here, I'll draft the doc PR

**Comment by shawarmaz** [comment] 2023-02-10 14:35
Glad things are finally clear.

This does require an update to the docs tho.

@mrousavy if you agree with what has been said here about MMKV usage, I'll draft up the doc PR

**Comment by arthurgeron-work** [comment] 2023-02-10 14:38
Shouldn't be just a update in the docs, most people that use this lib are unaware, in favor of avoiding crashes on thousands of project's I'd prepend delete to set by default, if that is proven to work; On top of that I'd place a warning in postinstall so everyone is aware.

**Comment by shawarmaz** [comment] 2023-02-10 14:43
Yes adding a warning in postinstall is a great idea. 

However, prepending writes with deletes at the lib-level breaks the semantics of this lib as an MMKV wrapper.

**Comment by mrousavy** [comment] 2023-02-10 22:18
@shawarmaz 100% agree with your comment.

**Comment by mrousavy** [comment] 2023-02-10 22:23
> It's not only falsely advertised, it's broken by design. Moving from async to mmkv is like switching to a bmw but that suddenly crashes into a lamp post if you push it too hard.

@arthurgeron-work @arthurgeron what? lol that does not make sense. Your understanding of what MMKV is for is wrong, it's not broken by design. 
I also mentioned that it is a key value storage a couple of times, I have compared it to other key value storage like solutions but that does not mean they are exactly equal and only differ in performance.

That's like comparing an Audi with a Ferrari, they are just not built for the same purpose.

**Comment by mrousavy** [comment] 2023-02-10 22:28
> On top of that I'd place a warning in postinstall so everyone is aware.

I think this is a terrible idea for multiple reasons:

1. No one reads that.
2. Warning people about a lib after installing it is the wrong place to do so. The docs (README) should explain what this library is for, and if people use it wrong it's on them.
3. What exactly should the warning be? That you should not spam a small key value storage with loads of data?

I am providing the code I wrote for free for anyone to download - that code runs in my apps in production without any problems and faster than any other library - if you use it correctly you benefit from it. If you use it wrong, call it false advertisement or "broken by design", then don't use it and don't comment here :)

**Comment by mrousavy** [comment] 2023-02-10 22:30
Now let's stop with spamming hateful comments - I have a productive idea: A `fastWrites: boolean` prop to the MMKV Config (constructor) that basically controls if writes should skip deleting to write more efficiently or not. We can leave it false by default, and if users want more speed they set it to true.

That way I don't get any annoying comments of people misunderstanding the reason why MMKV exists.

**Comment by arthurgeron** [comment] 2023-02-10 22:32
> > It's not only falsely advertised, it's broken by design. Moving from async to mmkv is like switching to a bmw but that suddenly crashes into a lamp post if you push it too hard.
> 
> @arthurgeron-work @arthurgeron what? lol that does not make sense. Your understanding of what MMKV is for is wrong, it's not broken by design. I also mentioned that it is a key value storage a couple of times, I have compared it to other key value storage like solutions but that does not mean they are exactly equal and only differ in performance.

I did not meant to sound offensive, that whole conversation was unecessary drama. Still, how would it not be fair? You've advertised specifically as a replacement for async storage, which is exactly the kind of usage that leads to crashes with this lib,  hence my previous example does make sense.

I understand the "issue" is in Tencent MMKV, but having a "just let people know" attitude instead of searching for a fix ( like creating a modified Tencent MMKV base ) isn't right, 2.6.x already brought a silent crash to older Android RN projects and now this is yet another silent issue that will be left as is. 
The minimum would be to add a change (if possible to 2.5.x) as well that avoids this problem entirely.

> > Warning people about a lib after installing it is the wrong place to do so. The docs (README) should explain what this library is for, and if people use it wrong it's on them.

README's hardly get read by devs that have had it installed for some time and it's a huge issue for many projects, and devs have already being misled to use it like async storage  so baffles me that it "it's on them".  I don't think warning them in every way possible is such a terrible idea.

**Comment by arthurgeron** [comment] 2023-02-10 22:33
> Now let's stop with spamming hateful comments - I have a productive idea: A `fastWrites: boolean` prop to the MMKV Config (constructor) that basically controls if writes should skip deleting to write more efficiently or not. We can leave it false by default, and if users want more speed they set it to true.
> 
> That way I don't get any annoying comments of people misunderstanding the reason why MMKV exists.

Sounds perfect, that'd fix the issue on current projects, I'd leave fastWrite "false" by default and explain the "dangers" of enabling it in the docs.

**Comment by KingAmo** [comment] 2023-02-13 05:21
i see a explain by MMKV in Chinese, see [here](https://github.com/Tencent/MMKV/wiki/design#%E7%A9%BA%E9%97%B4%E5%A2%9E%E9%95%BF)

**Comment by arthurgeron** [comment] 2023-02-13 14:06
So they did foresee that space allocation issue.. Interesting, seems like a better solution

**Comment by xmflsct** [comment] 2023-02-13 14:50
I am curious did anyone manage to run some benchmarks? How much *slower* it gets with and without fastWrite?

**Comment by harjotmalhi94** [comment] 2023-02-15 22:09
What is the recommended solution if we are limited to version 2.5.1 due to breaking changes in 2.6.0?

The changes [here](https://github.com/mrousavy/react-native-mmkv/issues/440#issuecomment-1421052424) do not seem to do the job and I can still see multiple copies of the same key in the Documents/mmkv file

**Comment by mrousavy** [comment] 2023-02-16 14:30
Okay since no one else did it, I created a minimal reproduceable example:

```tsx
const storage = new MMKV()

for (let i = 0; true; i++) {
  console.log(`Writing "test":"Some Value in here." to MMKV for the ${i}th time.`)
  storage.set('test', 'Some Value in here.')
}
```

This runs for a while. After writing for the 1.270.708th time, memory size reaches 500MB. So writing 1 million times to the same key makes it grow to 500MB of memory. 

Yes, that sounds like an issue. But this is a core MMKV issue, apparently they don't truncate the file after a few writes. I think this is due to `DEFAULT_MMAP_SIZE` being very large. I'll investigate this if I have some free time.

This is also an issue with the other rn mmkv library. 

I'm wondering if this is only happening in simulator due to more RAM being available? IDK what `DEFAULT_MMAP_SIZE` / `pagesize` is

**Comment by harjotmalhi94** [comment] 2023-02-16 14:48
Thanks for testing the limits @mrousavy 

I am attempting to patch version 2.5.1 with the same delete you did inside `set` here: https://github.com/mrousavy/react-native-mmkv/pull/509/files

But it still results in the old entries staying there and new ones being added. Any idea why the same patch in the older version does not work? Even prepending the set with a delete does not fix the issue:

```
setItem: (key, value) => {
    storage.delete(key)
    storage.set(key, value);
  }

**Comment by shawarmaz** [comment] 2023-02-16 16:33
Here's what the main developer of Tencent/MMKV at WeChat has to say:

>     MMKV won't increase to an unacceptable big size under normal usage. Before each growth, MMKV will always try to pack existing data to see if there's enough space for new commer.
>     However, if there's an unreasonable big value stored inside once, and if there's not enough space for that big value, MMKV might grow to an unexpected large size.
> 

https://github.com/Tencent/MMKV/issues/610#issuecomment-752015762

[As I mentioned earlier](https://github.com/mrousavy/react-native-mmkv/issues/440#issuecomment-1424412162), WeChat benchmarked MMKV against NSUserDefaults and SharedPreferences. Everybody should be referred to those to understand what MMKV is intended to be used for, high up in the docs. IMO this is the only part that needed to be fixed, otherwise people will keep trying to use MMKV as a database.

IMO fastWrites was a faux-pas, the naming implies one way to use it is for high volume of writes. However, the very fact WeChat ran benchmarks on something built for use cases that are not performance sensitive (storing auth token, color preferences, locale) is most likely the source of all this confusion.

And please don't fool yourselves, WeChat does not use MMKV as its database. It developed and uses a database for that: https://github.com/Tencent/wcdb

The whole point is if you even start hitting these issues in the first place with MMKV, the chances that you're using it for the wrong data approach 100%.

**Comment by matt-dalton** [comment] 2023-03-31 07:44
It would be great to have some guidance if possible on when we should consider MMKV (assuming we don't have knowledge of the underlying native storage systems mentioned).
If we're happy with slower writes (which from the benchmarking I've seen would still be quicker than async storage), are there any other issues with using MMKV as a direct swap for async storage? What kind of use-cases would be workable/unworkable?

e.g.
 - Persisting local state (e.g. larger JSON structures)
 - Using MMKV as an app cache (i.e. persisting data required to load screens, via something like Redux persist)
I would have thought you'd still see performance improvements in those cases using this over Async storage, but could be wrong

At what point does async storage the right choice? Any specific limits we should watch for?

**Comment by billnbell** [comment] 2023-05-01 05:19
Async Storage is limited size on IOS/Android. So that is why we even considered using MMKV and this library.

So what is the solution ?

**Comment by shawarmaz** [comment] 2023-05-01 11:07
@matt-dalton @billnbell 

Do not use MMKV nor AsyncStorage as a db. 

First off, they serve different use cases, and claiming it's faster than AsyncStorage fuels ongoing confusion. It's like saying a plane is faster than the car. There are numerous threads about this.

MMKV is designed for small data: color, locale, maybe tokens. AsyncStorage is good for larger, but not db/sqlite-scale data. 

If you want to store large amounts of data, for the love of God, use a ... database. 

Margelo (mrousavy's dev shop) just took over `react-native-quick-sqlite`, which is what should be used for larger data. So imo it won't be long before they clear out in the README this generalized lingering confusion of when to use `react-native-mmkv`

**Comment by billnbell** [comment] 2023-05-01 22:55
I am just using this for caching. And things like temp tokens.

So it is not a lot of data.

Seems like I am good then.

**Comment by matt-dalton** [comment] 2023-05-02 07:27
Yeah likewise. We're mainly storing simple settings flags etc.

What's your view on using MMKV for cached data @shawarmaz, assuming we turn fastWrites off? The chunks of data can be fairly large (because they represent the screen's state), but:
- They are cleared from the cache fairly quickly
- We don't care about persisting indefinitely
This seems like a use-case that would be ideal for MMKV from a performance perspective vs Async Storage. Is storage size the main danger here? It sounds like that only becomes a problem for enormous data sets from what I can see in this thread.

**Comment by billnbell** [comment] 2023-05-03 02:56
What is the actual size limit for a key - value pair?

**Comment by matt-dalton** [comment] 2023-05-11 07:41
Out of interest, what would you consider the best React Native choice for an app cache? By that I mean storing server data with a TTL, which could be reasonably large JSON-style objects for each screen, but nothing enormous.

I don't think async storage is a great choice here, because you're sending data across the bridge every time you restore or persist server data. But it sounds like MMKV is only a borderline fit. Do you think there's a better option? What do people typically use for native apps?

(Sorry if this is slightly stretching the scope of this discussion)

**Comment by evelant** [comment] 2023-06-10 16:37
@matt-dalton I'm also interested. 

I feel the current react-native-mmkv docs are a bit misleading if mmkv is indeed _not_ suitable for things like offline caching of small amounts of user data. I came to mmkv because I wanted a simple sync way to cache requests so my users can load the app offline. It seemed like a perfect alterantive to async storage for the job based on the readme/docs. After reading this thread I'm a bit confused however since it seems it is not intended for this use case.

 If there are good alternatives perhaps they can be mentioned in the readme along with a clarification about what mmkv is for? If I'm understanding this discussion correctly perhaps something along the lines of 

"MMKV is only designed to store small bits of state such as user preferences (under 1kb, infrequently written). If you're looking to cache requests or larger user data check out ----insert alternative here----"

added to the readme could be useful in reducing further confusion.

**Comment by mrousavy** [comment] 2023-06-12 09:10
Well tbh this is just purely your decision/needs for the app.

You want something sync? It has to be fast, so there are compromises - i.e. in-memory caching. -> [react-native-mmkv](https://github.com/mrousavy/react-native-mmkv)

You want something async? It can be a bit slower, i.e. optimized databases like SQL. -> [react-native-quick-sqlite](https://github.com/margelo/react-native-quick-sqlite)

**Comment by mrousavy** [comment] 2023-06-23 10:19
Hey - thanks! The podcast was really cool.

As far as I know the problem should be fixed or is not an actual problem - can anyone re-test this with the latest react-native-mmkv version and confirm?

**Comment by VirtualDOMinic** [comment] 2023-07-11 14:32
Perhaps a stupid question, but what tool/code were you (@mrousavy / @ryskin ) using to get the size of the storage?

I'm happy to give Marc's minimum reproducible example a go on an older version and again on the latest version (pending an upgrade of my app to RN 71) but want to be sure I'm measuring it correctly.

Thanks!

**Comment by mrousavy** [comment] 2023-07-17 11:09
Hey! Closing for now, if this issue still persists I'll re-open and take another look - but we need a reproduceable example app for that! (Make sure to test in release builds btw)

Thanks everyone :)

**Closed by mrousavy** 2023-07-17 11:09 UTC

**Comment by MaxToyberman** [comment] 2024-09-12 09:18
@mrousavy should the issue be fixed in 2.12.2 ? 

I wanted to use it for my offline mode but i guess that i can't (the object is not small)

Thanks

**Comment by mrousavy** [comment] 2024-09-12 09:20
fixed in V3.  Not in the old V2.

**Comment by MaxToyberman** [comment] 2024-09-12 09:23
Thanks @mrousavy ,  I am using the old architecture because it is in beta so i cant use V3 currently.

is there a workaround for this ?

**Comment by mrousavy** [comment] 2024-09-12 09:24
> I am using the old architecture because it is in beta

It's not in beta. In fact, new architecture is enabled by default in react-native 0.76.

> is there a workaround for this ?

Yes, upgrade to new arch & V3 😄 
I don't plan on fixing this for V2 unless it is funded / sponsored.

**Comment by MaxToyberman** [comment] 2024-09-12 09:30
Ok so they have to updated their docs ! 

Thank you @mrousavy

**Comment by shahzaib-cmyk** [comment] 2025-03-30 22:14
I'm using "react-native-mmkv": "^2.12.2", but I can't see the fastWrites option anywhere. How come? Upgrading to expo sdk 52 is too much of a hassle and not worth it. So I'm looking for this workaround

**Comment by petertoth-dev** [comment] 2025-04-27 02:47
> I'm using "react-native-mmkv": "^2.12.2", but I can't see the fastWrites option anywhere. How come? Upgrading to expo sdk 52 is too much of a hassle and not worth it. So I'm looking for this workaround

@shahzaib-cmyk unfortunately @mrousavy let us down with v2 :) "iTz bY dEzIgN"

**Comment by shahzaib-cmyk** [comment] 2025-04-27 11:08
> > I'm using "react-native-mmkv": "^2.12.2", but I can't see the fastWrites option anywhere. How come? Upgrading to expo sdk 52 is too much of a hassle and not worth it. So I'm looking for this workaround
> 
> [@shahzaib-cmyk](https://github.com/shahzaib-cmyk) unfortunately [@mrousavy](https://github.com/mrousavy) let us down with v2 :) "iTz bY dEzIgN"

sucks man :(, and it's advertised as a replacement to AsyncStorage as well. Currently, I'm just using it for storing very small boolean values only that don't change often, like isOnboardingScreenShown. For anything more, this issue makes it a deal breaker.

**Comment by VirtualDOMinic** [comment] 2025-04-29 14:21
> Yes, upgrade to new arch & V3 😄
> I don't plan on fixing this for V2 unless it is funded / sponsored.
@mrousavy thanks for your work on v3! I get your position on the above, but I'm also stuck on V2 for the time being, so I wonder if you can answer these - hopefully very quick - questions:

1. Are you able to provide a note and/or commit from V3 showing how you avoided the ever-expanding storage, so that one of us might manage to implement something similar for V2?
2. Are you able to estimate how much time (and therefore $$) it would take for you to implement this change to V2?
3. Can you (or anyone) confirm what they're doing to get the total size taken up by mmkv (as per my query [above](https://github.com/mrousavy/react-native-mmkv/issues/440#issuecomment-1630943836))? 
 
*[3] Not sure if there's a simpler/better way than what I've done? My best attempt is running in dev/debug on a local simulator, going to `~/Library/Developer/CoreSimulator/Devices/{my device udid}/data/Containers/Data/Application/{app udid}/Documents/mmkv` (simulator found via `xcrun simctl list | egrep '(Booted)'` and mmkv folder found via `find . -type d -name "mmkv" -print` which only yielded one result for this simulator) and then doing `du -ah .` to get an output like below:
```
 16K	./mmkv.default
 16K	./mmkv.default.crc
 16K	./<redacted>
 16K	./<redacted>.crc
 64K	.
```
