### ISSUE TITLE
`getString` fails on reload after calling `delete` with `encyptionKey` set in config

### ISSUE THREAD

**Issue by morganick** [mrousavy/react-native-mmkv#665] opened 2024-04-19 14:37 UTC
## Steps to reproduce:

- Set the `encryptionKey` in the config for your MMKV store
- Set a single key in the store
- Reload application to see the value you set pulling from the store with `getString`
- Remove the key from the store
- Set the single key in the store
- Reload the app with the developer menu
- 💥 Value is `undefined`
- Close the application
- Open application
- Value appears back on the screen

## Conditions to reproduce:

- `encryptionKey` set in config
- Item being stored is over 253 characters long
- Only one item is stored in MMKV

## Minimum Reproducible Example (MRE)

There are instructions in the README for installation:

https://github.com/morganick/mmkv-encryption-app-mre

I've documented permutations in the code that you can make that make it work again:

- https://github.com/morganick/mmkv-encryption-app-mre/blob/main/App.tsx#L14
- https://github.com/morganick/mmkv-encryption-app-mre/blob/main/App.tsx#L21

## Video

This happens on both iOS and Android.

| iOS 17.4  - iPhone 15 Pro |
|--------|
| <video src="https://github.com/mrousavy/react-native-mmkv/assets/151139/5d5b0f59-5521-4f52-a8f0-c5bda1ad7ec3" /> | 

## Logs

If you use the `create-expo-app` cli, you'll get MMKV logging in the metro output as follow:

```shell
[MMKVEncryptionTestApp] [I] <MMKV_IO.cpp:84::loadFromFile> loading [session] with 0 actual size, file size 16384, InterProcess 0, meta info version:0
[MMKVEncryptionTestApp] [I] <MMKV_IO.cpp:133::loadFromFile> loaded [session] with 0 key-values
[MMKVEncryptionTestApp] [I] <MMKV_IO.cpp:516::writeActualSize> [session] increase sequence to 1, crc 727578001, actualSize 4
iOS Bundled 37ms (node_modules/expo/AppEntry.js)
iOS Bundled 35ms (node_modules/expo/AppEntry.js)
[MMKVEncryptionTestApp] Installing global.mmkvCreateNewInstance...
[MMKVEncryptionTestApp] [W] <libMMKV.mm:76::+[MMKV initializeMMKV:logLevel:handler:]> already called +initializeMMKV before, ignore this request
[MMKVEncryptionTestApp] Installed global.mmkvCreateNewInstance!
[MMKVEncryptionTestApp] [D] <libMMKV.mm:919::+[MMKV mmapKeyWithMMapID:rootPath:]> mmapKey: session
iOS Bundled 37ms (node_modules/expo/AppEntry.js)
iOS Bundled 31ms (node_modules/expo/AppEntry.js)
[MMKVEncryptionTestApp] Installing global.mmkvCreateNewInstance...
[MMKVEncryptionTestApp] [W] <libMMKV.mm:76::+[MMKV initializeMMKV:logLevel:handler:]> already called +initializeMMKV before, ignore this request
[MMKVEncryptionTestApp] Installed global.mmkvCreateNewInstance!
[MMKVEncryptionTestApp] [D] <libMMKV.mm:919::+[MMKV mmapKeyWithMMapID:rootPath:]> mmapKey: session
[MMKVEncryptionTestApp] [E] <MMKV_OSX.cpp:225::getObject> InvalidProtocolBuffer truncatedMessage
iOS Bundled 37ms (node_modules/expo/AppEntry.js)
iOS Bundled 29ms (node_modules/expo/AppEntry.js)
[MMKVEncryptionTestApp] Installing global.mmkvCreateNewInstance...
[MMKVEncryptionTestApp] [W] <libMMKV.mm:76::+[MMKV initializeMMKV:logLevel:handler:]> already called +initializeMMKV before, ignore this request
[MMKVEncryptionTestApp] Installed global.mmkvCreateNewInstance!
[MMKVEncryptionTestApp] [D] <libMMKV.mm:919::+[MMKV mmapKeyWithMMapID:rootPath:]> mmapKey: session
[MMKVEncryptionTestApp] [E] <MMKV_OSX.cpp:225::getObject> InvalidProtocolBuffer truncatedMessage
[MMKVEncryptionTestApp] [I] <MMKV_OSX.cpp:99::setIsInBackground> g_isInBackground:1
[MMKVEncryptionTestApp] [I] <libMMKV.mm:308::+[MMKV didEnterBackground]> isInBackground:1
```

[!NOTE]
The `InvalidProtocolBuffer truncatedMessage` shows up in the logs when this breaks.

Special thanks to @frankcalise for being a sounding board while I tracked this down and testing out the MRE.

**Comment by scblason** [comment] 2024-04-26 18:48
I have a similar issue with version 2.12.2. Before I was using 2.9.0 and I don't have any issues (and we just updated MMKV, we didn't made any code changes).
But repro steps are similar to the ones mentioned above. The `getString` fails to get the valid data in an ecrypted store after applying a delete and set operation.
In our case:
- We refresh the app
- We read the store (getString OK)
- We delete the key from the store
- We set a new value for that same key
- We do a getString from that key FAILS

**Comment by scblason** [comment] 2024-05-06 22:26
An update on this: I get the same error in 2.9.0. This started to happen when we updated to RN 0.73.x

**Comment by Akumzy** [comment] 2024-05-07 11:59
Facing the same issue here

**Comment by mrousavy** [comment] 2024-05-08 11:12
Two things:

1. Does this bug also happen when **not** using encryption?
2. Can you reproduce this in the **current** example app? This one uses new-arch, react-native-mmkv V3. Please test this.

**Comment by Romick2005** [comment] 2024-05-17 08:48
1. It is not happen when **not** using encryption.

**Comment by mrousavy** [comment] 2024-05-17 14:39
Okay gotcha - maybe a bug with encryption. Did you test if react-native-mmkv V3 fixes this issue? (requires new architeceture)

**Comment by scblason** [comment] 2024-05-17 15:10
> Okay gotcha - maybe a bug with encryption. Did you test if react-native-mmkv V3 fixes this issue? (requires new architeceture)

I tested with latest v3 version and I had the same issue, but I'm not working with the new architecture though

**Comment by morganick** [comment] 2024-05-21 12:17
@mrousavy it happens only when encryption is turned on. I pulled in the code from my repro project into the example application, but haven't had a chance to put it through its paces yet. I'll try to get to that this afternoon and report back.

Thanks for your patience 🙇

**Comment by kulak91** [comment] 2024-06-04 18:14
Having the same issue with access_token (~800 symbols length). 
Delete token from the storage => Save new => Get this token => Result is empty => Save again => Get This token => it works.
Waiting for a fix

**Comment by mrousavy** [comment] 2024-06-04 19:46
getObject is in V2, try V3.

**Comment by mrousavy** [comment] 2024-06-12 15:41
Hey all - I'm closing this now since it looks like I fixed the issue in the V3 turbomodule rewrite :) Thanks all!

**Closed by mrousavy** 2024-06-12 15:41 UTC
