### ISSUE TITLE
Question: What is the difference between react-native-mmkv & react-native-mmkv-storage ?

### ISSUE THREAD

**Issue by KJA-Tsx** [mrousavy/react-native-mmkv#301] opened 2022-01-24 15:09 UTC
I am wondering why do we have two libraries doing the same job, which one shall I use ?

**Comment by Hirbod** [comment] 2022-01-24 16:44
Duplicate of https://github.com/mrousavy/react-native-mmkv/issues/100

Using the search function isn't that hard :)

**Comment by mrousavy** [comment] 2022-01-25 08:44
As @Hirbod said, I explained the differences in detail here: https://github.com/mrousavy/react-native-mmkv/issues/100#issuecomment-886477361

**Closed** 2022-01-25 08:44 UTC

**Comment by KJA-Tsx** [comment] 2022-01-25 10:02
> As @Hirbod said, I explained the differences in detail here: [#100 (comment)](https://github.com/mrousavy/react-native-mmkv/issues/100#issuecomment-886477361)

Hey, I have read the comparison  section , I am really hesitant at this point, one thing that got my attention is that everything is synchronous in this library, does this make a difference ?

**Comment by mrousavy** [comment] 2022-01-25 10:07
> everything is synchronous in this library, does this make a difference?

Well yes, it does.

## Faster

It's faster than a Bridge call. By magnitudes. Like, really really fast.

## Easy access

Consider the following code:

```ts
const isLoggedIn = storage.getBoolean('is-logged-in')
function App() {
  return isLoggedIn ? <Main /> : <Login />
}
```

This is fast, shows the correct UI (Main or Login) immediately, and does not cause any re-renders. **This is how it works with my library.**

Let's try to build the same UI with an asynchronous UI:


```ts
function App() {
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    (async () => {
      const data = await storage.getBooleanAsync('is-logged-in')
      setIsLoggedIn(data)
      setIsLoading(false)
    })()
  }, [])

  if (isLoading) return <Loading />
  return isLoggedIn ? <Main /> : <Login />
}
```

**Comment by mrousavy** [comment] 2022-01-25 12:28
Here are the docs for Encryption: [iOS](https://github.com/Tencent/MMKV/wiki/iOS_advance#encryption) & [Android](https://github.com/Tencent/MMKV/wiki/android_advance#encryption)

Quote:

> By default MMKV stores all key-values in plain text on file, relying on Android's sandbox to make sure the file is encrypted. Should you worry about information leaking, you can choose to encrypt MMKV.

**Comment by mrousavy** [comment] 2022-01-25 20:59
Everything will be deleted when the user uninstalls your app.

**Comment by thoth-seshat** [comment] 2023-06-30 06:56
Can I encrypt without providing a key? Or do I always need to provide a key. I'm a bit new to this but I'm comparing this to SecureStore (with expo). SecureStore mentions it uses Keychain for iOS at least. I'm guessing this doesn't use keychain or anything like that correct?
