### ISSUE TITLE
Support for macOS and Windows

### ISSUE THREAD

**Issue by ShivamJoker** [mrousavy/react-native-mmkv#279] opened 2022-01-06 12:30 UTC
Hey it would be great to have the support for desktop version of react native as well.

**Comment by mrousavy** [comment] 2022-01-06 12:38
yeah, that would indeed be great

**Comment by mrousavy** [comment] 2022-01-06 12:38
duplicate of https://github.com/mrousavy/react-native-mmkv/issues/12

**Comment by ShivamJoker** [comment] 2022-01-06 12:42
@mrousavy Not sure about windows but macOS should be easy because the library already works on iOS.

**Closed** 2022-01-19 10:52 UTC
