### ISSUE TITLE
Values not getting immediately updated in same session between Android and RN shared instances

### ISSUE THREAD

**Issue by shubhamguptadream11** [mrousavy/react-native-mmkv#784] opened 2024-12-29 07:56 UTC
What we are trying to do:

We are using **MMKV** to share data between **Native** and **React Native environments** within the same app. The goal is for both environments to access and update shared data seamlessly, using the same MMKV instance, so that updates to a key on one platform are immediately available on the other platform.

**What's the problem:**
When we update a value on one platform (either Native or React Native), the updated value does not become available on the other platform until the app is restarted or brought back from the background. Although the instance is shared across both platforms, MMKV’s caching layer does not sync real-time updates across platforms. This results in outdated values being read on the platform that didn’t make the last update.

**Expected behaviour:**
Any updates to a key on one platform (Native or React Native) should immediately reflect on the other platform without requiring an app restart or session change.

For now we had written our own JSI implementation to call Android instance and use it in RN side. Let me know your thoughts on this.

**Comment by mrousavy** [comment] 2024-12-30 12:02
Hey - duplicate of https://github.com/mrousavy/react-native-mmkv/issues/783, see [my answer on that issue](https://github.com/mrousavy/react-native-mmkv/issues/783#issuecomment-2565264529)

**Comment by mrousavy** [comment] 2024-12-30 12:03
Well actually sorry it's not the same issue as 783, but it's similar.

I guess the best approach to this is to use the JS instnaces as a single source of truth. Maybe via callbacks.

**Closed by mrousavy** 2024-12-30 12:02 UTC

**Comment by shubhamguptadream11** [comment] 2024-12-30 13:31
@mrousavy  Currently we are doing reverse of this. Using Android instance on RN using JSI. Is there any problem in this approach?

**Comment by shubhamguptadream11** [comment] 2025-01-07 06:12
@mrousavy Can we re open this issue again as it is not resolved yet.

**Comment by denisoliveira** [comment] 2025-02-11 15:44
@shubhamguptadream11 if you are using a version 2.X, here is what we analyzed and implemented on our side to achieve interoperability:

## First make the the library shared

```
diff --git a/node_modules/react-native-mmkv/MMKV/Core/CMakeLists.txt b/node_modules/react-native-mmkv/MMKV/Core/CMakeLists.txt
index 681efdf..fe9e7af 100644
--- a/node_modules/react-native-mmkv/MMKV/Core/CMakeLists.txt
+++ b/node_modules/react-native-mmkv/MMKV/Core/CMakeLists.txt
@@ -66,7 +66,8 @@ project(core)
 add_library(core
 
         # Sets the library as a shared library.
-        STATIC
+        # STATIC
+        SHARED
 
         # Provides a relative path to your source file(s).
         MMKV.h
@@ -159,6 +160,11 @@ find_library(zlib
 IF (NOT zlib)
     target_compile_definitions(core PUBLIC MMKV_EMBED_ZLIB=1)
 ELSE()
-    target_link_libraries(core ${zlib})
+    IF(UNIX AND (NOT APPLE))
+      find_library(log-lib log)
+      target_link_libraries(core ${zlib} ${log-lib})
+    ELSE()
+        target_link_libraries(core ${zlib})
+    ENDIF()
 ENDIF()
```

## Second edit or create a CMakeLists.txt and append the mmkv core library

In a CMakeLists.txt file:

```
# MMKV
set(MMKV_CORE_DIR ../../node_modules/react-native-mmkv/MMKV/Core)

add_subdirectory(../../node_modules/react-native-mmkv/MMKV/Core core)

 add_library(mmkv SHARED
         src/main/cpp/MMKV/native-bridge.cpp
 )

 set_target_properties(mmkv PROPERTIES
        CXX_STANDARD 17
        CXX_EXTENSIONS OFF
        POSITION_INDEPENDENT_CODE ON
)

include_directories(
        ${MMKV_CORE_DIR}
        src/main/cpp
)

target_link_libraries(mmkv
        log
        core
)
```

# Third copy the source from Android [MMKV](https://github.com/Tencent/MMKV/tree/master/Android/MMKV/mmkv/src/main)
- Files to ignore flutter-bridge.cpp, AndroidManifest.xml
