### ISSUE TITLE
Error in CI build when use cache

### ISSUE THREAD

**Issue by AZagatti** [mrousavy/react-native-mmkv#547] opened 2023-06-12 23:49 UTC
Hello, 
I recently upgraded React Native to 0.71 and upgraded the library as well, after that I started taking the following error and realized that this error is happening when the Github Actions cache from `node_modules` is used, any solution for new versions?

```
> Task :react-native-mmkv:externalNativeBuildCleanRelease FAILED
Clean reactnativemmkv-armeabi-v7a, core-armeabi-v7a
C/C++: CMake Warning at /usr/local/lib/android/sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   /usr/local/lib/android/sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
C/C++:   .cxx/RelWithDebInfo/2v2rj525/armeabi-v7a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
C/C++:   CMakeLists.txt:1 (project)
C/C++: CMake Error in CMakeLists.txt:
C/C++:   Imported target "ReactAndroid::jsi" includes non-existent path
C/C++:     "/home/runner/.gradle/caches/transforms-3/5d7ed713ee7fff40b3a935790bd46ebb/transformed/jetified-react-android-0.71.8-release/prefab/modules/jsi/include"
C/C++:   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
C/C++:   * The path was deleted, renamed, or moved to another location.
C/C++:   * An install or uninstall procedure did not complete successfully.
C/C++:   * The installation package was faulty and references files it does not
C/C++:   provide.
C/C++: CMake Generate step failed.  Build files cannot be regenerated correctly.
C/C++: ninja: error: rebuilding 'build.ninja': subcommand failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv:externalNativeBuildCleanRelease'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/runner/work/project/project/node_modules/react-native-mmkv/android/.cxx/RelWithDebInfo/2v2rj525/armeabi-v7a'
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  FAILED: build.ninja 
  /usr/local/lib/android/sdk/cmake/3.18.1/bin/cmake --regenerate-during-build -S/home/runner/work/project/project/node_modules/react-native-mmkv/android -B/home/runner/work/project/project/node_modules/react-native-mmkv/android/.cxx/RelWithDebInfo/2v2rj525/armeabi-v7a
  
  C++ build system [clean] failed while executing:
      /usr/local/lib/android/sdk/cmake/3.18.1/bin/ninja \\
        -C \\
        /home/runner/work/project/project/node_modules/react-native-mmkv/android/.cxx/RelWithDebInfo/2v2rj525/armeabi-v7a \\
        clean
    from /home/runner/work/project/project/node_modules/react-native-mmkv/android
  CMake Warning at /usr/local/lib/android/sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /usr/local/lib/android/sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
    .cxx/RelWithDebInfo/2v2rj525/armeabi-v7a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
    CMakeLists.txt:1 (project)
  
  
  CMake Error in CMakeLists.txt:
    Imported target "ReactAndroid::jsi" includes non-existent path
  
      "/home/runner/.gradle/caches/transforms-3/5d7ed713ee7fff40b3a935790bd46ebb/transformed/jetified-react-android-0.71.8-release/prefab/modules/jsi/include"
  
    in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  
    * The path was deleted, renamed, or moved to another location.
  
    * An install or uninstall procedure did not complete successfully.
  
    * The installation package was faulty and references files it does not
    provide.
  
  
  
  CMake Generate step failed.  Build files cannot be regenerated correctly.
  ninja: error: rebuilding 'build.ninja': subcommand failed

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 10s
34 actionable tasks: 28 executed, 6 up-to-date
```

**Comment by marcinolek** [comment] 2023-06-21 23:26
Hi, 
I've recently encountered a similar error. Like in your case, something was missing inside /.gradle/caches/transforms.. folder. After clearing caches, removing node_modules etc., I found out that a setting in my .zshrc (.bashrc) file:
`export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` was causing a build failure.
So if anyone has a problem with android build, I'd recommend:
1. Check your environment settings for possibly unwanted vars
2. Uninstall older versions of NDK (keep 25), and/or CMAKE (3.18.x works fine for me) 

I can confirm that reenabling `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` causes the build failure to reappear, so it probably needs to be fixed in mmkv.

**Comment by mrousavy** [comment] 2023-07-17 10:56
Hey! Sorry I cannot reproduce the issue here. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)

**Closed by mrousavy** 2023-07-17 10:56 UTC

**Comment by namnh-0652** [comment] 2024-01-17 10:13
@AZagatti @marcinolek did you find the solution for Github Action build? I got this issue, too

**Comment by aymather** [comment] 2024-07-05 15:11
I am running into this as well, any updates?

**Comment by abdullah-tsx** [comment] 2024-10-21 06:19
ran into same issue. did following steps

1. Open Adndroid Studio settings.
2. open sdk tools.
3. update cmake and ndk to latest.

this fixed my issues

**Comment by Dat-Mobile** [comment] 2025-01-24 09:50
I also faced this issue from my CI build, I clear the cache and the build is success
