### ISSUE TITLE
Data is not persisted on web via localStorage

### ISSUE THREAD

**Issue by maximilize** [mrousavy/react-native-mmkv#457] opened 2022-09-22 11:45 UTC
Somehow using mmkv on electron does not persist the data. We are using react-native-web, creating a `storage.web.ts` file fixed this issue for us. Maybe it helps to find the issue...

```typescript
/* global localStorage */

export default {
  clearAll: () => localStorage.clear(),

  // setters
  setBoolean: (key: string, value: boolean) =>
    localStorage.setItem(key, JSON.stringify(value)),
  setNumber: (key: string, value: number) =>
    localStorage.setItem(key, JSON.stringify(value)),
  setString: (key: string, value: string) =>
    localStorage.setItem(key, JSON.stringify(value)),
  setObj: (key: string, value: object) =>
    localStorage.setItem(key, JSON.stringify(value)),

  // getters
  getAllKeys: () => Object.keys(localStorage),

  getBoolean: (key: string, defaultValue?: boolean) => {
    const value = localStorage.getItem(key);
    if (value == null) {
      return defaultValue;
    }
    return JSON.parse(value);
  },

  getNumber: (key: string, defaultValue?: number) => {
    const value = localStorage.getItem(key);
    return value === null ? defaultValue : JSON.parse(value);
  },

  getString: (key: string, defaultValue?: string) => {
    const value = localStorage.getItem(key);
    return value === null ? defaultValue : JSON.parse(value);
  },

  getObj: (key: string, defaultValue?: object) => {
    const value = localStorage.getItem(key);
    return value === null ? defaultValue : JSON.parse(value);
  },

  // delete
  delete: (key: string) => localStorage.delete(key),
  contains: (key: string) => localStorage.getItem(key) !== null,
};
```

**Comment by mrousavy** [comment] 2022-09-23 09:30
Hm, weird. Could you set breakpoints there to see if that's being used at all: https://github.com/mrousavy/react-native-mmkv/blob/master/src/createMMKV.web.ts

**Comment by bombillazo** [comment] 2022-11-28 11:50
Hey, related to this issue, `interface MMKVConfiguration` should be updated since these:

```ts

  if (config.encryptionKey != null) {
    throw new Error("MMKV: 'encryptionKey' is not supported on Web!");
  }
  if (config.path != null) {
    throw new Error("MMKV: 'path' is not supported on Web!");
  }
```

Are compared to null yet their types are only either string or undefined.

**Comment by mrousavy** [comment] 2022-11-28 12:41
@bombillazo This is using `!=`, not `!==`. It is not a strict comparison, so it works either way.

See [this example.](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmYAnAngBygS3AaTimAXhgFcwATOAM0zDnICgnRIQAbOAOjZAHMAKBMnRZc+IsTAk2bAJQMWEdlx4ChqDNjB4ChPTCkzZQA)

**Comment by bombillazo** [comment] 2022-11-28 12:46
It logically works, but TypeScript will not like it because it is implicit.
![image](https://user-images.githubusercontent.com/44002321/204281260-898ddfe3-114b-468c-9771-aed9c9bed800.png)

**Comment by maximilize** [comment] 2022-11-28 12:50
To make it most flexible, how about using `if (!config.path)`? I think this is the most readable way...

**Comment by mrousavy** [comment] 2022-11-28 13:54
> It logically works, but TypeScript will not like it because it is implicit:

Yea if you assign it, yes. I only use `null` for the implicit comparison. To assign it, I'd use `undefined`.

> I think this is the most readable way...

I disagree, to me that is only a boolean (isValid, !isValid) check, not a nullability check. 

I think I just got used to it from C#, where `== null` or `!= null` are the norm. It doesn't make a difference in code, but we can change it to `== undefined` or `!= undefined`.

**Comment by bombillazo** [comment] 2022-11-28 14:10
Yeah, I haven't tested it but I'm assuming if I assign them to `undefined`, I won't get the errors thrown. But there it would work on web as expected.

**Comment by mrousavy** [comment] 2023-07-17 11:11
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)

**Closed by mrousavy** 2023-07-17 11:11 UTC
