### ISSUE TITLE
Stopped working in react-native-web

### ISSUE THREAD

**Issue by gituser8796** [mrousavy/react-native-mmkv#731] opened 2024-09-01 17:42 UTC
Uncaught ReferenceError: exports is not defined

It was working perfectly before 3.x.x

**Comment by gituser8796** [comment] 2024-09-02 08:03
It's standard react-native-web

**Comment by amutsch** [comment] 2024-09-02 17:21
@gituser8796 I haven't booted my project in a couple weeks but this was working in web the when I last used it, what version of the library are you using and what version of react native?

**Comment by gituser8796** [comment] 2024-09-03 11:23
@amutsch - I'm using react-native@0.75.1 and react-native-mmkv@3.02

In order to get web working I have to manually set react-native-mmkv@2.12.2 (which prevents mobile form loading)

Thank you!

**Comment by amutsch** [comment] 2024-09-03 11:45
@gituser8796 That means you are not using react native new architecture.  3.x.x only works with new architecture enabled in react native.  This is working as designed according to the documentation that @mrousavy has with the release.

**Comment by amutsch** [comment] 2024-09-06 02:54
I upgraded my project tonight to 75.2 and mmkv 3.0.2, my android build was working on my windows machine, I will build and test my web, ios and android from my mac when I get back on Sunday

**Comment by arasrezaei** [comment] 2024-09-08 19:27
i got "Identifier 'module' has already been declared", a line before `function getMMKVTurboModule() {`

**Comment by amutsch** [comment] 2024-09-10 02:29
I have everything working just fine. 
Versions:
RN75.2, 
mmkv - 3.0.2
react-native-web: 0.19.12

Webpack is spitting out some warnings due to how turbomodules need to be defined but it is not preventing starting or using the web side.
Android I had to clear the build folders and then everything built fine
IOS I had to clear the podfile.lock and gemfile.lock and everything is working fine there now as well.

Following best practice for a major upgrade of my main libs I cleared my node_modules and yarn.lock file as well.  Everything is working as I expect it to.


Hope this helps but not seeing any issues in my setup.  Kicking off my CICD on my update here shortly, I've gone from 74.x and version 2.12.0 to new arch with 3.0.6-beta to 75.2

**Comment by gituser8796** [comment] 2024-09-13 15:12
hi @amutsch any progress on this one? it's becoming an issue for use to use this repo - so any fix would be appreciated!

**Comment by amutsch** [comment] 2024-09-13 17:11
@gituser8796 I'm going to need more details as all you are providing is a reference Error.  I outlined what versions I used at 74 and 75 and before and after new arch and everything is working for me.  As I mentioned react-native-web is now required to use 3.x lib(it wasn't with 2.x) but other than some startup warnings everything is working fine on my side, 

What relevant lib versions are you using(RN, RNWeb, Webpack/vite/other)  Compiling this to working web opens up a whole new suite of items to check.  Can your create a small reproduction scenario independent of your app?  Is your app available to public on github, if so I can take a look there too.

**Comment by ISnowFoxI** [comment] 2024-09-14 19:47
Are you guys using expo or react-native cli?

**Comment by mrousavy** [comment] 2024-09-15 09:38
Thanks for all your help guys 🙏🖤

**Comment by amutsch** [comment] 2024-10-16 10:17
@mrousavy no feedback for over a month, I think we can close this, both myself and ISnowFoxl have verified working with expo and RN-cli with RN-web

**Comment by mrousavy** [comment] 2024-10-16 10:19
awesome thank you!

**Closed by mrousavy** 2024-10-16 10:19 UTC
Labels: help wanted

**Comment by dppo** [comment] 2024-10-17 01:34
This error should be exported by the ESM method used on the react-native-web side, such as the vite used. TurboModuleRegistry does not exist on the react-native-web side, so in
`import {TurboModuleRegistry} from 'react-native';`
An error will be reported when

```
alias: {
      'react-native': 'react-native-web',
      'react-native-mmkv': 'react-native-mmkv/lib/commonjs',
    },
```
This method can be used temporarily, but I think a better method may be needed.

**Comment by joarkosberg** [comment] 2024-11-15 13:19
Had similar errors when upgrading and running on web, @dppo solution worked for me :)

**Versions:**
RN (bare without expo) - 0.76.2,
mmkv - 3.1.0
react-native-web: 0.19.13
Vite - 5.4.8

**Error:**
```
✘ [ERROR] No matching export in "../node_modules/react-native-web/dist/index.js" for import "TurboModuleRegistry"

    ../node_modules/react-native-mmkv/lib/module/NativeMmkv.js:3:9:
      3 │ import { TurboModuleRegistry } from 'react-native';
        ╵          ~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "../node_modules/react-native-mmkv/lib/module/NativeMmkv.js" for import "Configuration"

    ../node_modules/react-native-mmkv/lib/module/index.js:5:15:
      5 │ export { Mode, Configuration } from './NativeMmkv';
```

**Comment by amutsch** [comment] 2024-11-15 13:24
From my experience the no matching export does not stop startup and running.  There is a known issue where Typescript interfaces have to be in the same file as the TurboModule which means we have to import the TurboModuleRegistry for those interfaces.  In my project webpack throughs warnings not errors for those and the web side still works perfectly fine, I haven't looked at Vite to see how it handles it but you may need to find a way to tell vite to ignore those errors
