### ISSUE TITLE
Expo SDK 52 Development build does not work on Android

### ISSUE THREAD

**Issue by codan84** [mrousavy/react-native-mmkv#781] opened 2024-12-11 23:16 UTC
I have latest Expo development build with `"newArchEnabled": true`.  
react-native-mmkv 3.1.0
react-native 0.76.2  

Code:
```
const storage = new MMKV({ id: 'auth', encryptionKey: 'foo-bar' })
```

Works on iOS development build alright. But on Android:
```
 (NOBRIDGE) ERROR  Warning: Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. 
    at ContextNavigator (http://192.168.4.133:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:154170:24)
    at ExpoRoot (http://192.168.4.133:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:154119:28)
    at App
    at ErrorToastContainer (http://192.168.4.133:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:236721:24)
    at ErrorOverlay
    at withDevTools(ErrorOverlay) (http://192.168.4.133:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:116819:27)
    at RCTView
    at View (http://192.168.4.133:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:38161:43)
    at RCTView
    at View (http://192.168.4.133:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:38161:43)
    at AppContainer (http://192.168.4.133:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:38033:25)
    at main(RootComponent) (http://192.168.4.133:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:106272:28)
```

Output of `react-native config`:
```
//***//
    "react-native-mmkv": {
      "root": "/Users/dang/workspace/priv/orderly-client-mobile/node_modules/react-native-mmkv",
      "name": "react-native-mmkv",
      "platforms": {
        "ios": {
          "podspecPath": "/Users/dang/workspace/priv/orderly-client-mobile/node_modules/react-native-mmkv/react-native-mmkv.podspec",
          "version": "3.1.0",
          "configurations": [],
          "scriptPhases": []
        },
        "android": {
          "sourceDir": "/Users/dang/workspace/priv/orderly-client-mobile/node_modules/react-native-mmkv/android",
          "packageImportPath": "import com.mrousavy.mmkv.MmkvPackage;",
          "packageInstance": "new MmkvPackage()",
          "buildTypes": [],
          "libraryName": "RNMmkvSpec",
          "componentDescriptors": [],
          "cmakeListsPath": "/Users/dang/workspace/priv/orderly-client-mobile/node_modules/react-native-mmkv/android/build/generated/source/codegen/jni/CMakeLists.txt",
          "cxxModuleCMakeListsModuleName": "react-native-mmkv",
          "cxxModuleCMakeListsPath": "/Users/dang/workspace/priv/orderly-client-mobile/node_modules/react-native-mmkv/android/CMakeLists.txt",
          "cxxModuleHeaderName": "NativeMmkvModule",
          "isPureCxxDependency": false
        }
      }
    },
//***//
```

Some gradlew logs:
```
> Configure project :react-native-mmkv
[react-native-mmkv] Thank you for using react-native-mmkv ❤️
[react-native-mmkv] If you enjoy using react-native-mmkv, please consider sponsoring this project: https://github.com/sponsors/mrousavy

> Task :react-native-mmkv:generateCodegenSchemaFromJavaScript
> Task :react-native-mmkv:generateCodegenArtifactsFromSchema

> Task :react-native-mmkv:preBuild
> Task :react-native-mmkv:preDebugBuild

> Task :react-native-mmkv:writeDebugAarMetadata
> Task :react-native-mmkv:generateDebugResValues
> Task :react-native-mmkv:generateDebugResources
> Task :react-native-mmkv:packageDebugResources

> Task :react-native-mmkv:extractDeepLinksDebug
> Task :react-native-mmkv:processDebugManifest
> Task :react-native-mmkv:compileDebugLibraryResources
> Task :react-native-mmkv:parseDebugLocalResources
> Task :react-native-mmkv:generateDebugRFile
> Task :react-native-mmkv:generateDebugBuildConfig
> Task :react-native-mmkv:javaPreCompileDebug
> Task :react-native-mmkv:compileDebugJavaWithJavac
> Task :react-native-mmkv:bundleLibCompileToJarDebug

Note: /home/expo/workingdir/build/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-mmkv:mergeDebugShaders
> Task :react-native-mmkv:compileDebugShaders NO-SOURCE
> Task :react-native-mmkv:generateDebugAssets UP-TO-DATE
> Task :react-native-mmkv:packageDebugAssets

> Task :react-native-mmkv:bundleLibRuntimeToJarDebug
> Task :react-native-mmkv:processDebugJavaRes NO-SOURCE

> Task :react-native-mmkv:mergeDebugJniLibFolders
> Task :react-native-mmkv:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-mmkv:copyDebugJniLibsProjectOnly
```

Android model/version: OnePlus 5, Android 10.  
Gradle 8.10.2  
Any idea what might be going wrong?

**Comment by sebbalex** [comment] 2024-12-12 10:33
same here, @mrousavy please, could you have a look

**Comment by codan84** [comment] 2024-12-12 10:52
Funny enough it works on an emulator just fine 🤷

**Comment by mrousavy** [comment] 2024-12-12 11:07
Duplicate of https://github.com/mrousavy/react-native-mmkv/issues/776. Yes, this is not caused by react-native-mmkv - please stop pinging me

**Closed by mrousavy** 2024-12-12 11:07 UTC

**Comment by uguraktas** [comment] 2024-12-13 10:27
@mrousavy both tickets are closed but there is no solution. You can at least let people discuss and find solutions, right?

**Comment by EvgeniiZaets** [comment] 2025-06-20 12:22
For me, the solution was to remove an app from my device and install it again.
